window.EXAMS = window.EXAMS || {};
(function(){
const T1="Characteristics of Living Organisms", T2="Variety of Living Organisms", T3="Cells & Magnification",
      T4="Respiration & Respirometer", T5="Movement In & Out of Cells", T6="Biological Molecules & Food Tests",
      T7="Nutrition in Humans & Plants", T8="Gas Exchange", T9="CORMMSS & Practical Skills";

const mcq = [
/* ---------- 1. Characteristics of living organisms ---------- */
{t:T1,d:1,
 q:`Which list contains <b>only</b> characteristics shared by all living organisms?`,
 th:`ข้อใดประกอบด้วยลักษณะที่สิ่งมีชีวิต<b>ทุกชนิด</b>มีร่วมกันเท่านั้น`,
 o:[`growth, photosynthesis, excretion`,`movement, respiration, response to surroundings, reproduction`,`digestion, excretion, growth`,`breathing, reproduction, nutrition`],
 a:1,
 s:[["หลักการ","ลักษณะของสิ่งมีชีวิต (Edexcel) มี 8 ข้อ: <span class='key'>nutrition, respiration, excretion, response to surroundings, movement, control of internal conditions, reproduction, growth &amp; development</span> (จำง่าย ๆ ว่า MRS C GREN)"],
    ["ตัดตัวเลือก","<ul><li>A: <b>photosynthesis</b> ทำได้เฉพาะพืชและสาหร่าย สัตว์และเห็ดราทำไม่ได้</li><li>C: <b>digestion</b> (การย่อยในทางเดินอาหาร) ไม่ใช่ทุกสิ่งมีชีวิต เช่น พืชไม่มีระบบย่อยอาหาร</li><li>D: <b>breathing</b> (การหายใจเข้าออก) ไม่เท่ากับ <b>respiration</b> (การสลายอาหารในเซลล์เพื่อปล่อยพลังงาน) พืชและแบคทีเรียไม่ได้ breathe</li></ul>"],
    ["สรุป","B ทุกคำอยู่ในลักษณะ 8 ข้อ ✅ <b>คำตอบ B</b>"]]},

{t:T1,d:1,
 q:`Which of the following is an example of <b>excretion</b>?`,
 th:`ข้อใดเป็นตัวอย่างของ<b>การขับถ่ายของเสีย (excretion)</b>`,
 o:[`Removal of undigested fibre as faeces`,`Release of amylase in saliva`,`Removal of carbon dioxide produced by respiration`,`Shedding of hair`],
 a:2,
 s:[["นิยาม","<b>Excretion</b> = การกำจัด<span class='key'>ของเสียที่เกิดจากเมแทบอลิซึม (metabolic waste)</span> ในเซลล์ และสารที่มีมากเกินความต้องการ เช่น CO<sub>2</sub> จาก respiration, urea จากการสลายกรดอะมิโน"],
    ["แยกให้ออก","<b>Egestion</b> (การขับอุจจาระ) ไม่ใช่ excretion เพราะเส้นใยที่ย่อยไม่ได้<b>ไม่เคยเข้าสู่เซลล์</b> ไม่ได้เกิดจากเมแทบอลิซึม ส่วนการหลั่งเอนไซม์เป็น <b>secretion</b>"],
    ["สรุป","CO<sub>2</sub> เกิดจาก respiration ในเซลล์ จึงเป็น metabolic waste ✅ <b>คำตอบ C</b>"]]},

{t:T1,d:2,
 q:`A car uses fuel and oxygen, releases carbon dioxide and water, and can move. Which reason best explains why a car is <b>not</b> a living organism?`,
 th:`รถยนต์ใช้เชื้อเพลิงและออกซิเจน ปล่อย CO<sub>2</sub> และน้ำ และเคลื่อนที่ได้ เหตุผลใดอธิบายได้ดีที่สุดว่าทำไมรถยนต์<b>ไม่ใช่</b>สิ่งมีชีวิต`,
 o:[`It does not release energy from fuel`,`It does not produce waste products`,`It cannot move by itself`,`It cannot grow, develop or reproduce`],
 a:3,
 s:[["วิเคราะห์","สิ่งมีชีวิตต้องแสดง<b>ครบทุกลักษณะ</b> ไม่ใช่เพียงบางข้อ รถยนต์แสดงลักษณะคล้าย respiration (เผาเชื้อเพลิง ปล่อยพลังงาน), excretion (ปล่อยไอเสีย) และ movement"],
    ["หาจุดที่ขาด","รถยนต์ <span class='key'>ไม่เติบโต (growth) ไม่พัฒนา และสืบพันธุ์ (reproduction) ไม่ได้</span> รวมถึงไม่ได้ตอบสนองต่อสิ่งเร้าด้วยตัวเอง"],
    ["ตัดตัวเลือก","A, B, C เป็นสิ่งที่รถยนต์ <b>ทำได้</b> ตามโจทย์ จึงใช้เป็นเหตุผลไม่ได้"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:T1,d:1,
 q:`Which characteristic of living organisms is described as "keeping conditions inside the body, such as temperature and water content, within narrow limits"?`,
 th:`ลักษณะของสิ่งมีชีวิตข้อใดหมายถึง "การรักษาสภาวะภายในร่างกาย เช่น อุณหภูมิและปริมาณน้ำ ให้อยู่ในช่วงแคบ ๆ"`,
 o:[`Control of internal conditions (homeostasis)`,`Nutrition`,`Excretion`,`Response to surroundings`],
 a:0,
 s:[["นิยาม","<b>Control of internal conditions</b> หรือ <span class='key'>homeostasis</span> คือการรักษาสภาพแวดล้อมภายในให้คงที่ เช่น อุณหภูมิร่างกาย 37 °C ระดับน้ำตาลในเลือด ปริมาณน้ำ"],
    ["ตัดตัวเลือก","B = การได้รับสารอาหาร/พลังงาน, C = การกำจัดของเสียจากเมแทบอลิซึม (ช่วย homeostasis ได้แต่ไม่ใช่นิยามนี้), D = sensitivity ตอบสนองต่อสิ่งเร้าภายนอก"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

/* ---------- 2. Variety of living organisms ---------- */
{t:T2,d:1,
 q:`An organism has a body made of thread-like hyphae forming a mycelium. Its cell walls contain chitin and it feeds by secreting enzymes onto dead material. Which group does it belong to?`,
 th:`สิ่งมีชีวิตชนิดหนึ่งมีลำตัวเป็นเส้นใย hyphae รวมกันเป็น mycelium ผนังเซลล์มี chitin และกินอาหารโดยหลั่งเอนไซม์ออกไปย่อยซากสิ่งมีชีวิต จัดอยู่ในกลุ่มใด`,
 o:[`Bacteria`,`Protoctists`,`Fungi`,`Plants`],
 a:2,
 s:[["จับคีย์เวิร์ด","<span class='key'>hyphae → mycelium</span>, <span class='key'>chitin cell wall</span>, <span class='key'>saprotrophic nutrition</span> (หลั่งเอนไซม์ออกนอกเซลล์แล้วดูดซึมสารที่ย่อยแล้ว) เป็นลักษณะเฉพาะของ <b>Fungi</b> เช่น <i>Mucor</i>"],
    ["เทียบกลุ่มอื่น","แบคทีเรียเป็นเซลล์เดียว ไม่มีนิวเคลียส; พืชมีผนังเซลล์เป็น <b>cellulose</b>; protoctist ส่วนใหญ่เป็นเซลล์เดียวมีนิวเคลียส"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:T2,d:2,
 q:`Which structure is found in a bacterial cell but <b>not</b> in a human cheek cell?`,
 th:`โครงสร้างใดพบในเซลล์แบคทีเรีย แต่<b>ไม่</b>พบในเซลล์เยื่อบุกระพุ้งแก้มของคน`,
 o:[`Plasmid`,`Nucleus`,`Mitochondrion`,`Cell membrane`],
 a:0,
 s:[["ทบทวนโครงสร้างแบคทีเรีย","แบคทีเรียมี: cell wall (ไม่ใช่ cellulose), cell membrane, cytoplasm, <span class='key'>circular chromosome (DNA)</span>, <span class='key'>plasmids</span> บางชนิดมี flagellum และ slime capsule"],
    ["ตัดตัวเลือก","<ul><li>B, C: <b>แบคทีเรียไม่มี</b> nucleus และ mitochondria แต่เซลล์คนมี (กลับด้านกับโจทย์)</li><li>D: cell membrane มีทั้งสองแบบ</li></ul>"],
    ["สรุป","Plasmid = วง DNA ขนาดเล็ก พบในแบคทีเรีย ไม่พบในเซลล์คน ✅ <b>คำตอบ A</b>"]]},

{t:T2,d:2,
 q:`Which statement about viruses is correct?`,
 th:`ข้อความใดเกี่ยวกับไวรัสถูกต้อง`,
 o:[`They have a cell wall made of cellulose`,`They carry out respiration to release energy`,`They contain both a nucleus and ribosomes`,`They can only reproduce inside living host cells`],
 a:3,
 s:[["โครงสร้างไวรัส","ไวรัส<b>ไม่ใช่เซลล์</b> มีเพียง <span class='key'>protein coat (capsid)</span> ห่อหุ้ม <span class='key'>DNA หรือ RNA</span> ไม่มี cytoplasm, ribosome, nucleus"],
    ["การสืบพันธุ์","ไวรัสเป็น <b>parasite</b> ที่ต้องเข้าไปใช้กลไกของ<b>เซลล์เจ้าบ้าน</b>สร้างไวรัสใหม่ นอกเซลล์ไม่แสดงลักษณะของสิ่งมีชีวิต เช่น ไม่ respire"],
    ["สรุป","A, B, C ผิดทั้งหมดเพราะไวรัสไม่มีโครงสร้างเซลล์ ✅ <b>คำตอบ D</b>"]]},

{t:T2,d:1,
 q:`Which organism is a <b>protoctist</b>?`,
 th:`สิ่งมีชีวิตใดเป็น <b>โพรทอคติสต์ (protoctist)</b>`,
 o:[`<i>Mucor</i>`,`<i>Lactobacillus bulgaricus</i>`,`<i>Chlorella</i>`,`<i>Pneumococcus</i>`],
 a:2,
 s:[["ตัวอย่างตามหลักสูตร","<ul><li>Fungi: <i>Mucor</i>, yeast (<i>Saccharomyces</i>)</li><li>Bacteria: <i>Lactobacillus bulgaricus</i>, <i>Pneumococcus</i></li><li>Protoctists: <span class='key'><i>Chlorella</i></span> (คล้ายพืช มีคลอโรพลาสต์), <i>Amoeba</i> (คล้ายสัตว์), <i>Plasmodium</i> (ก่อโรคมาลาเรีย)</li></ul>"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:T2,d:2,
 q:`Which row correctly shows the storage carbohydrate in plants and in animals?`,
 th:`แถวใดแสดงคาร์โบไฮเดรตสะสมในพืชและในสัตว์ได้ถูกต้อง`,
 o:[`plants: glycogen · animals: starch`,`plants: starch or sucrose · animals: glycogen`,`plants: cellulose · animals: glycogen`,`plants: glucose · animals: cellulose`],
 a:1,
 s:[["หลักการ","<span class='key'>พืช</span> เก็บคาร์โบไฮเดรตเป็น <b>starch</b> (และ sucrose) ส่วน<span class='key'>สัตว์</span> เก็บเป็น <b>glycogen</b> ในตับและกล้ามเนื้อ"],
    ["ตัดตัวเลือก","C: <b>cellulose</b> เป็นคาร์โบไฮเดรตโครงสร้าง (ผนังเซลล์) ไม่ใช่สารสะสม; A สลับกัน; D สัตว์ไม่มี cellulose"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:T2,d:2,
 q:`Which pathogen is a <b>virus</b> that infects plants, causing a mosaic pattern of discolouration on leaves?`,
 th:`เชื้อก่อโรคใดเป็น<b>ไวรัส</b>ที่ติดเชื้อในพืช ทำให้ใบมีลายด่างเป็นหย่อม (mosaic)`,
 o:[`<i>Plasmodium</i>`,`Tobacco mosaic virus`,`<i>Pneumococcus</i>`,`Influenza virus`],
 a:1,
 s:[["แยกประเภทเชื้อ","<ul><li><i>Plasmodium</i> = protoctist ก่อโรคมาลาเรียในคน</li><li><i>Pneumococcus</i> = แบคทีเรีย ก่อโรคปอดบวม</li><li>Influenza virus = ไวรัสแต่ติดเชื้อในคน/สัตว์</li><li><span class='key'>Tobacco mosaic virus (TMV)</span> = ไวรัสในพืช ทำให้ใบด่าง สร้างคลอโรฟิลล์ได้น้อยลง</li></ul>"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

/* ---------- 3. Cells & magnification ---------- */
{t:T3,d:1,
 q:`Which structures are found in a palisade mesophyll cell but <b>not</b> in a liver cell?`,
 th:`โครงสร้างใดพบในเซลล์ palisade mesophyll ของใบ แต่<b>ไม่</b>พบในเซลล์ตับ`,
 o:[`cell membrane, nucleus, ribosomes`,`mitochondria, cytoplasm, cell wall`,`nucleus, chloroplasts, vacuole`,`cell wall, chloroplasts, large permanent vacuole`],
 a:3,
 s:[["หลักการ","โครงสร้างที่มี<b>เฉพาะเซลล์พืช</b>: <span class='key'>cellulose cell wall</span>, <span class='key'>chloroplasts</span>, <span class='key'>large permanent vacuole</span> (มี cell sap)"],
    ["ตัดตัวเลือก","A: มีทั้งสองเซลล์; B: mitochondria และ cytoplasm มีในเซลล์ตับด้วย; C: nucleus มีในเซลล์ตับ"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:T3,d:1,
 q:`What is the function of ribosomes?`,
 th:`ไรโบโซมทำหน้าที่อะไร`,
 o:[`Protein synthesis`,`Releasing energy by aerobic respiration`,`Controlling what enters and leaves the cell`,`Absorbing light for photosynthesis`],
 a:0,
 s:[["หน้าที่ออร์แกเนลล์","<ul><li><span class='key'>Ribosome</span> → สังเคราะห์โปรตีน (translation)</li><li>Mitochondrion → aerobic respiration</li><li>Cell membrane → ควบคุมการเข้าออกของสาร</li><li>Chloroplast → ดูดกลืนแสงเพื่อสังเคราะห์ด้วยแสง</li></ul>"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:T3,d:2,
 q:`In a drawing, a cell measures <b>45 mm</b> long. The real length of the cell is <b>30 µm</b>. What is the magnification of the drawing?`,
 th:`ในภาพวาด เซลล์หนึ่งยาว <b>45 mm</b> ขณะที่ความยาวจริงคือ <b>30 µm</b> กำลังขยายของภาพวาดเป็นเท่าใด`,
 o:[`×1.5`,`×150`,`×1500`,`×15 000`],
 a:2,
 s:[["สูตร","<span class='key'>Magnification = image size ÷ actual size</span> (ทั้งสองค่าต้องเป็น<b>หน่วยเดียวกัน</b>)"],
    ["แปลงหน่วย","1 mm = 1000 µm → 45 mm = 45 × 1000 = <b>45 000 µm</b>"],
    ["คำนวณ","Magnification = 45 000 ÷ 30 = <b>×1500</b>"],
    ["กับดัก","ถ้าลืมแปลงหน่วยจะได้ 45 ÷ 30 = ×1.5 (ตัวเลือก A) ✅ <b>คำตอบ C</b>"]]},

{t:T3,d:2,
 q:`An electron micrograph shows a mitochondrion <b>20 mm</b> long at a magnification of <b>×10 000</b>. What is the actual length of the mitochondrion?`,
 th:`ภาพจากกล้องจุลทรรศน์อิเล็กตรอนแสดงไมโทคอนเดรียยาว <b>20 mm</b> ที่กำลังขยาย <b>×10 000</b> ความยาวจริงของไมโทคอนเดรียคือเท่าใด`,
 o:[`0.2 µm`,`2 µm`,`20 µm`,`200 µm`],
 a:1,
 s:[["สูตร","<span class='key'>Actual size = image size ÷ magnification</span> (สามเหลี่ยม I-A-M: I = A × M)"],
    ["คำนวณ","20 mm ÷ 10 000 = 0.002 mm"],
    ["แปลงหน่วย","0.002 mm × 1000 = <b>2 µm</b> (ขนาดไมโทคอนเดรียทั่วไป 1–10 µm สมเหตุสมผล)"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:T3,d:1,
 q:`Which sequence shows the levels of organisation from smallest to largest?`,
 th:`ลำดับใดแสดงระดับการจัดระบบของสิ่งมีชีวิตจากเล็กไปใหญ่ได้ถูกต้อง`,
 o:[`cell → organelle → tissue → organ → organ system`,`organelle → tissue → cell → organ → organ system`,`organelle → cell → organ → tissue → organ system`,`organelle → cell → tissue → organ → organ system`],
 a:3,
 s:[["นิยามแต่ละระดับ","<ul><li><b>Organelle</b>: โครงสร้างในเซลล์ เช่น mitochondrion</li><li><b>Cell</b>: หน่วยพื้นฐานของสิ่งมีชีวิต</li><li><b>Tissue</b>: กลุ่มเซลล์ชนิดเดียวกันทำงานร่วมกัน เช่น muscle tissue</li><li><b>Organ</b>: เนื้อเยื่อหลายชนิดรวมกัน เช่น stomach</li><li><b>Organ system</b>: อวัยวะหลายอย่างทำงานร่วมกัน เช่น digestive system</li></ul>"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:T3,d:2,
 q:`Cubes of agar containing phenolphthalein (pink) are placed in acid. The acid diffuses in and the cubes turn colourless. Which cube takes the <b>longest</b> to become completely colourless?`,
 th:`นำก้อนวุ้นที่มี phenolphthalein (สีชมพู) ไปแช่ในกรด กรดแพร่เข้าไปทำให้วุ้นไม่มีสี ก้อนใดใช้เวลา<b>นานที่สุด</b>จึงไม่มีสีทั้งก้อน`,
 o:[`3 cm × 3 cm × 3 cm`,`2 cm × 2 cm × 2 cm`,`1 cm × 1 cm × 1 cm`,`0.5 cm × 0.5 cm × 0.5 cm`],
 a:0,
 s:[["คำนวณ SA:V","<div class='tbl'><table><tr><th>ด้าน (cm)</th><th>SA (cm²)</th><th>V (cm³)</th><th>SA:V</th></tr><tr><td>0.5</td><td>1.5</td><td>0.125</td><td>12 : 1</td></tr><tr><td>1</td><td>6</td><td>1</td><td>6 : 1</td></tr><tr><td>2</td><td>24</td><td>8</td><td>3 : 1</td></tr><tr><td>3</td><td>54</td><td>27</td><td>2 : 1</td></tr></table></div>"],
    ["เหตุผล","ก้อนใหญ่มี <span class='key'>SA:V ต่ำที่สุด</span> พื้นที่ผิวให้กรดแพร่เข้าต่อปริมาตรน้อย และ<b>ระยะทางจากผิวถึงใจกลางไกลที่สุด</b> (1.5 cm) จึงใช้เวลานานที่สุด"],
    ["เชื่อมโยง","นี่คือเหตุผลที่สิ่งมีชีวิตขนาดใหญ่ต้องมีพื้นผิวแลกเปลี่ยนแก๊สพิเศษ (เช่น ถุงลม) และระบบลำเลียง"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:T3,d:2,
 q:`Which adaptation helps a red blood cell carry out its function?`,
 th:`การปรับตัวใดช่วยให้เซลล์เม็ดเลือดแดงทำหน้าที่ได้`,
 o:[`Many mitochondria to release energy for active transport`,`A long extension to increase surface area for absorbing water`,`No nucleus, leaving more space for haemoglobin`,`A thick cell wall to prevent bursting in capillaries`],
 a:2,
 s:[["หน้าที่","เม็ดเลือดแดงลำเลียง O<sub>2</sub> โดยใช้ <span class='key'>haemoglobin</span>"],
    ["การปรับตัว","<ul><li><b>ไม่มีนิวเคลียส</b> → มีที่บรรจุ haemoglobin มากขึ้น</li><li>รูปร่าง <b>biconcave disc</b> → SA:V สูง แพร่ O<sub>2</sub> เร็ว</li><li>ยืดหยุ่น ผ่านเส้นเลือดฝอยได้</li></ul>"],
    ["ตัดตัวเลือก","A: เม็ดเลือดแดงไม่มีไมโทคอนเดรีย; B: เป็นลักษณะของ root hair cell; D: เซลล์สัตว์<b>ไม่มี cell wall</b>"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

/* ---------- 4. Respiration ---------- */
{t:T4,d:1,
 q:`Which word equation represents aerobic respiration?`,
 th:`สมการข้อใดแสดงการหายใจระดับเซลล์แบบใช้ออกซิเจน`,
 o:[`carbon dioxide + water → glucose + oxygen`,`glucose + oxygen → carbon dioxide + water`,`glucose → lactic acid`,`glucose → ethanol + carbon dioxide`],
 a:1,
 s:[["สมการ","<span class='key'>glucose + oxygen → carbon dioxide + water</span> (+ พลังงานเก็บในรูป ATP)<br>C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + 6O<sub>2</sub> → 6CO<sub>2</sub> + 6H<sub>2</sub>O"],
    ["ตัดตัวเลือก","A = photosynthesis; C = anaerobic ในกล้ามเนื้อสัตว์; D = anaerobic ในยีสต์ (fermentation)"],
    ["ข้อควรระวัง","ในสมการ<b>ไม่ใส่คำว่า energy เป็นสาร</b> เพราะพลังงานไม่ใช่สารเคมี (เขียนแยกว่า energy released)"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:T4,d:1,
 q:`Which substances are produced when yeast respires anaerobically?`,
 th:`ยีสต์หายใจแบบไม่ใช้ออกซิเจนแล้วได้สารใด`,
 o:[`lactic acid only`,`carbon dioxide and water`,`lactic acid and carbon dioxide`,`ethanol and carbon dioxide`],
 a:3,
 s:[["เปรียบเทียบ","<ul><li>ยีสต์ (และพืช): <span class='key'>glucose → ethanol + carbon dioxide</span> ใช้ทำขนมปัง (CO<sub>2</sub> ทำให้ฟู) และเบียร์/ไวน์ (ethanol)</li><li>กล้ามเนื้อคน: glucose → lactic acid (ไม่มี CO<sub>2</sub>)</li></ul>"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:T4,d:2,
 q:`Which statement about anaerobic respiration in human muscle is correct?`,
 th:`ข้อความใดเกี่ยวกับการหายใจแบบไม่ใช้ออกซิเจนในกล้ามเนื้อคนถูกต้อง`,
 o:[`It produces lactic acid and releases much less energy per glucose than aerobic respiration`,`It produces ethanol, which causes muscle fatigue`,`It releases more energy per glucose than aerobic respiration`,`It uses oxygen to break down lactic acid in the muscle`],
 a:0,
 s:[["สมการ","glucose → <span class='key'>lactic acid</span> + พลังงาน<b>เล็กน้อย</b> (glucose ถูกสลายไม่สมบูรณ์ พลังงานยังค้างอยู่ใน lactic acid)"],
    ["Oxygen debt","หลังออกกำลังกาย เราหายใจแรงต่อเพื่อนำ O<sub>2</sub> ไปสลาย lactic acid (ส่วนใหญ่ที่ตับ) เรียกว่า <b>oxygen debt</b>"],
    ["ตัดตัวเลือก","B: ethanol เกิดในยีสต์; C: กลับด้าน; D: การหายใจแบบนี้เกิดขึ้นเมื่อ O<sub>2</sub> ไม่พอ และการกำจัด lactic acid เกิดที่ตับเป็นหลัก"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:T4,d:2,
 q:`In a respirometer containing germinating seeds, what is the purpose of the soda lime?`,
 th:`ในเครื่องวัดการหายใจ (respirometer) ที่มีเมล็ดกำลังงอก soda lime มีหน้าที่อะไร`,
 o:[`It absorbs oxygen so the seeds respire anaerobically`,`It releases carbon dioxide for the seeds`,`It absorbs carbon dioxide, so movement of the liquid shows the volume of oxygen taken in`,`It provides water for germination`],
 a:2,
 s:[["หลักการทำงาน","เมล็ดดูด O<sub>2</sub> และปล่อย CO<sub>2</sub> ในปริมาตรใกล้เคียงกัน ถ้าไม่กำจัด CO<sub>2</sub> ปริมาตรแก๊สแทบไม่เปลี่ยน"],
    ["บทบาท soda lime","<span class='key'>Soda lime ดูดซับ CO<sub>2</sub></span> ดังนั้นเมื่อเมล็ดใช้ O<sub>2</sub> ปริมาตรแก๊สในหลอดลดลง ความดันลด → หยดของเหลวสีเคลื่อน<b>เข้าหาเมล็ด</b> ระยะที่เคลื่อน ∝ O<sub>2</sub> ที่ถูกใช้"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:T4,d:3,
 q:`In a respirometer, the coloured liquid moves <b>15 mm</b> along a capillary tube of internal <b>diameter 2.0 mm</b>. Using volume = πr² × distance, what volume of oxygen was absorbed? (π = 3.14)`,
 th:`ในเครื่องวัดการหายใจ หยดของเหลวสีเคลื่อนไป <b>15 mm</b> ในหลอดแคปิลลารีที่มี<b>เส้นผ่านศูนย์กลางภายใน 2.0 mm</b> ใช้สูตร ปริมาตร = πr² × ระยะทาง ปริมาตร O<sub>2</sub> ที่ถูกดูดไปเป็นเท่าใด (π = 3.14)`,
 o:[`0.188 cm³`,`0.047 cm³`,`47.1 cm³`,`0.094 cm³`],
 a:1,
 s:[["หารัศมี","r = diameter ÷ 2 = 2.0 ÷ 2 = <b>1.0 mm</b> (กับดักคือใช้ 2.0 เป็น r)"],
    ["คำนวณ","V = 3.14 × (1.0)² × 15 = <b>47.1 mm³</b>"],
    ["แปลงหน่วย","1 cm³ = 1000 mm³ → 47.1 ÷ 1000 = <span class='key'>0.0471 cm³</span>"],
    ["ตัวเลือกหลอก","A (0.188) = ใช้ diameter เป็นรัศมี; C (47.1) = ลืมแปลงหน่วย ✅ <b>คำตอบ B</b>"]]},

{t:T4,d:2,
 q:`A student sets up a second respirometer identical to the first but containing glass beads instead of germinating seeds. Why?`,
 th:`นักเรียนตั้ง respirometer ชุดที่สองแบบเดียวกันทุกอย่าง แต่ใส่ลูกปัดแก้วแทนเมล็ดที่กำลังงอก เพื่ออะไร`,
 o:[`To provide extra oxygen for the seeds`,`To absorb carbon dioxide`,`To increase the rate of respiration`,`As a control, to show that any movement is due to the living seeds and not changes in temperature or pressure`],
 a:3,
 s:[["แนวคิด Control","ลูกปัดแก้ว<span class='key'>ปริมาตรเท่ากัน</span>กับเมล็ด แต่ไม่มีชีวิต ไม่หายใจ ใช้เป็น <b>control</b>"],
    ["เหตุผล","ถ้าหยดของเหลวในชุด control เคลื่อน แสดงว่าเกิดจาก<b>อุณหภูมิหรือความดันบรรยากาศเปลี่ยน</b> ต้องนำค่านี้ไปปรับแก้ผลของชุดที่มีเมล็ด"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

/* ---------- 5. Movement in & out of cells ---------- */
{t:T5,d:1,
 q:`Which is the best definition of diffusion?`,
 th:`ข้อใดเป็นนิยามของการแพร่ (diffusion) ที่ดีที่สุด`,
 o:[`Movement of water through a partially permeable membrane`,`Movement of particles against a concentration gradient using energy`,`Net movement of particles from a region of higher concentration to a region of lower concentration`,`Movement of particles from low to high concentration through a membrane`],
 a:2,
 s:[["นิยาม","<b>Diffusion</b> = <span class='key'>net movement</span> ของอนุภาคจากบริเวณที่มีความเข้มข้น<b>สูง → ต่ำ</b> (down a concentration gradient) เป็นกระบวนการ passive ไม่ใช้พลังงานจากเซลล์"],
    ["ทำไมต้อง net","อนุภาคเคลื่อนที่<b>แบบสุ่ม</b>ทุกทิศ แต่ฝั่งที่มีอนุภาคมากกว่ามีโอกาสเคลื่อนออกมากกว่า การเคลื่อนสุทธิจึงไปทางความเข้มข้นต่ำ จนถึง equilibrium"],
    ["ตัดตัวเลือก","A = osmosis; B = active transport; D = ทิศผิด"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:T5,d:2,
 q:`A plant cell is placed in a concentrated sodium chloride solution. What happens to the cell?`,
 th:`นำเซลล์พืชไปแช่ในสารละลายโซเดียมคลอไรด์เข้มข้น จะเกิดอะไรกับเซลล์`,
 o:[`Water leaves by osmosis, the vacuole shrinks and the membrane pulls away from the cell wall`,`Water enters by osmosis and the cell bursts`,`Salt enters by osmosis and the cell becomes turgid`,`Nothing happens because the cell wall is fully permeable`],
 a:0,
 s:[["เปรียบเทียบ water potential","สารละลายเกลือเข้มข้นมี water potential <b>ต่ำกว่า</b>ใน cell sap → น้ำเคลื่อน<b>ออก</b>จากเซลล์ผ่าน partially permeable membrane โดย <span class='key'>osmosis</span>"],
    ["ผลที่เห็น","vacuole หดเล็ก, cytoplasm หด, cell membrane ดึงหลุดออกจาก cell wall → เซลล์ <span class='key'>plasmolysed</span> ช่องว่างระหว่างผนังกับเยื่อหุ้มถูกเติมด้วยสารละลายเกลือ (เพราะ cell wall ให้สารผ่านได้อย่างอิสระ)"],
    ["ตัดตัวเลือก","B: เซลล์พืชไม่แตกเพราะมี cell wall และน้ำไหลออกไม่ใช่เข้า; C: osmosis คือการเคลื่อนของ<b>น้ำ</b>ไม่ใช่เกลือ; D: แม้ cell wall ยอมให้ผ่าน แต่ cell membrane เป็น partially permeable"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:T5,d:2,
 q:`Red blood cells are placed in distilled water. What happens and why?`,
 th:`นำเม็ดเลือดแดงไปใส่ในน้ำกลั่น จะเกิดอะไรขึ้น และเพราะเหตุใด`,
 o:[`They shrink because water leaves by osmosis`,`They become turgid because the cell wall resists expansion`,`They stay the same because distilled water is isotonic`,`They swell and burst because water enters by osmosis and there is no cell wall`],
 a:3,
 s:[["วิเคราะห์","น้ำกลั่นมี water potential <b>สูงกว่า</b>ในเซลล์ (hypotonic) → น้ำเข้าเซลล์โดย osmosis"],
    ["ความต่างจากเซลล์พืช","เซลล์สัตว์<span class='key'>ไม่มี cell wall</span> ต้านแรงดัน เซลล์จึงบวมจนแตก (<b>lysis / haemolysis</b>) ขณะที่เซลล์พืชจะเต่ง (turgid) แต่ไม่แตก"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:T5,d:3,
 q:`Potato cylinders were placed in sucrose solutions for 1 hour. The table shows the percentage change in mass.
 <div class='tbl'><table><tr><th>Sucrose (mol/dm³)</th><td>0.0</td><td>0.2</td><td>0.4</td><td>0.6</td></tr><tr><th>% change in mass</th><td>+12</td><td>+5</td><td>−3</td><td>−10</td></tr></table></div>
 Estimate the concentration that has the same water potential as the potato cells.`,
 th:`นำชิ้นมันฝรั่งแช่ในสารละลายซูโครสนาน 1 ชั่วโมง ได้ผลตามตาราง ความเข้มข้นใดโดยประมาณที่มี water potential เท่ากับเซลล์มันฝรั่ง`,
 o:[`0.2 mol/dm³`,`0.3 mol/dm³`,`0.4 mol/dm³`,`0.6 mol/dm³`],
 a:1,
 s:[["หลักการ","ที่ water potential เท่ากัน (isotonic) จะ<span class='key'>ไม่มีการเคลื่อนสุทธิของน้ำ</span> → มวลเปลี่ยน <b>0%</b> ต้องหาจุดที่กราฟตัดแกน x"],
    ["อ่านข้อมูล","0.2 → +5% (ยังได้น้ำ), 0.4 → −3% (เสียน้ำ) จุด 0% จึงอยู่ระหว่าง 0.2 กับ 0.4"],
    ["ประมาณ (interpolation)","จาก +5 ไป −3 เปลี่ยน 8 หน่วยในช่วง 0.2 mol/dm³ → ลดลง 5 หน่วยใช้ 0.2 × 5/8 = 0.125 → 0.2 + 0.125 ≈ <b>0.33 mol/dm³</b> ใกล้ 0.3 ที่สุด"],
    ["ทำไมใช้ % change","ชิ้นมันฝรั่งแต่ละชิ้นมีมวลเริ่มต้นไม่เท่ากัน การใช้ % ทำให้เปรียบเทียบได้ยุติธรรม ✅ <b>คำตอบ B</b>"]]},

{t:T5,d:2,
 q:`Root hair cells absorb mineral ions from soil by active transport. Which condition would <b>reduce</b> the rate of mineral ion uptake?`,
 th:`เซลล์ขนรากดูดแร่ธาตุจากดินด้วย active transport สภาวะใดจะ<b>ลด</b>อัตราการดูดแร่ธาตุ`,
 o:[`A higher concentration of ions in the soil`,`Warm temperature around 25 °C`,`Waterlogged soil with little oxygen`,`More root hairs on the root`],
 a:2,
 s:[["หลักการ","Active transport ลำเลียงไอออน<b>ทวน concentration gradient</b> (ในดินน้อย → ในเซลล์มาก) ต้องใช้ <span class='key'>พลังงาน (ATP) จาก aerobic respiration</span>"],
    ["เชื่อมโยง","ดินที่น้ำขัง (waterlogged) มี O<sub>2</sub> น้อย → เซลล์รากหายใจแบบใช้ O<sub>2</sub> ได้น้อย → ATP น้อย → active transport ช้าลง"],
    ["ตัดตัวเลือก","A, B, D ล้วนเพิ่มหรือไม่ลดอัตรา"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:T5,d:1,
 q:`Which change would <b>decrease</b> the rate of diffusion of oxygen across an exchange surface?`,
 th:`การเปลี่ยนแปลงใดจะ<b>ลด</b>อัตราการแพร่ของออกซิเจนผ่านพื้นผิวแลกเปลี่ยนแก๊ส`,
 o:[`Increasing the temperature`,`Increasing the thickness of the exchange surface`,`Increasing the concentration gradient`,`Increasing the surface area`],
 a:1,
 s:[["ปัจจัยที่มีผลต่อการแพร่","<ul><li>Concentration gradient ↑ → อัตรา ↑</li><li>Surface area ↑ → อัตรา ↑</li><li>Temperature ↑ → อนุภาคมีพลังงานจลน์มากขึ้น → อัตรา ↑</li><li><span class='key'>Distance (ความหนา) ↑ → อัตรา ↓</span></li></ul>"],
    ["สรุป","พื้นผิวที่หนาขึ้น ทำให้ระยะทางการแพร่ยาวขึ้น ✅ <b>คำตอบ B</b>"]]},

/* ---------- 6. Biological molecules ---------- */
{t:T6,d:1,
 q:`Which chemical element is found in proteins but <b>not</b> in carbohydrates or lipids?`,
 th:`ธาตุใดพบในโปรตีน แต่<b>ไม่</b>พบในคาร์โบไฮเดรตหรือลิพิด`,
 o:[`Carbon`,`Hydrogen`,`Oxygen`,`Nitrogen`],
 a:3,
 s:[["องค์ประกอบธาตุ","<ul><li>Carbohydrates: C, H, O</li><li>Lipids: C, H, O</li><li>Proteins: C, H, O, <span class='key'>N</span> (บางชนิดมี S)</li></ul>"],
    ["เหตุผล","ไนโตรเจนอยู่ในหมู่ amino (−NH<sub>2</sub>) ของกรดอะมิโน นี่คือเหตุผลที่พืชต้องการ <b>nitrate</b> เพื่อสร้างโปรตีน"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:T6,d:1,
 q:`Which row correctly matches each large molecule with the smaller units it is made from?`,
 th:`แถวใดจับคู่โมเลกุลใหญ่กับหน่วยย่อยที่ประกอบขึ้นได้ถูกต้อง`,
 o:[`starch → glucose; protein → amino acids; lipid → fatty acids and glycerol`,`starch → amino acids; protein → glucose; lipid → glycerol only`,`starch → fatty acids; protein → amino acids; lipid → glucose`,`starch → sucrose; protein → fatty acids; lipid → amino acids`],
 a:0,
 s:[["หน่วยย่อย","<ul><li><b>Starch, glycogen, cellulose</b> → <span class='key'>glucose</span></li><li><b>Protein</b> → <span class='key'>amino acids</span></li><li><b>Lipid (triglyceride)</b> → <span class='key'>3 fatty acids + 1 glycerol</span> ต่อกันด้วย ester bond</li></ul>"],
    ["เสริม","การต่อหน่วยย่อยเป็นปฏิกิริยา <b>condensation</b> (ปล่อยน้ำ) การย่อยกลับเป็น <b>hydrolysis</b> (ใช้น้ำ)"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:T6,d:2,
 q:`Benedict's solution is added to four food samples and heated in a water bath. Which colour shows the <b>highest</b> concentration of reducing sugar?`,
 th:`เติมสารละลายเบเนดิกต์ลงในตัวอย่างอาหาร 4 ชนิดแล้วให้ความร้อนในอ่างน้ำร้อน สีใดแสดงว่ามีน้ำตาลรีดิวซ์<b>มากที่สุด</b>`,
 o:[`Blue`,`Green`,`Brick red`,`Yellow`],
 a:2,
 s:[["วิธีทดสอบ","เติม Benedict's ปริมาตรเท่ากัน → ให้ความร้อนใน<span class='key'>อ่างน้ำร้อน (~80 °C) ประมาณ 5 นาที</span>"],
    ["ลำดับสี","<b>blue</b> (ไม่มี) → green → yellow → orange → <span class='key'>brick red</span> (มากที่สุด)"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:T6,d:2,
 q:`A food sample gives these results: iodine stays orange-brown; Benedict's stays blue after heating; biuret turns purple; ethanol emulsion test gives a cloudy white layer. Which nutrients does the food contain?`,
 th:`ตัวอย่างอาหารให้ผลดังนี้: ไอโอดีนยังเป็นสีส้มน้ำตาล, เบเนดิกต์ยังคงสีฟ้าหลังให้ความร้อน, ไบยูเร็ตเป็นสีม่วง, ทดสอบ emulsion ด้วยเอทานอลได้ชั้นขาวขุ่น อาหารนี้มีสารอาหารใด`,
 o:[`Starch and protein`,`Protein and lipid`,`Reducing sugar and lipid`,`Starch, protein and lipid`],
 a:1,
 s:[["แปลผลทีละการทดสอบ","<div class='tbl'><table><tr><th>การทดสอบ</th><th>ผลบวก</th><th>ผลที่ได้</th><th>สรุป</th></tr><tr><td>Iodine</td><td>blue-black</td><td>orange-brown</td><td>ไม่มี starch</td></tr><tr><td>Benedict's</td><td>brick red</td><td>blue</td><td>ไม่มี reducing sugar</td></tr><tr><td>Biuret</td><td>purple/lilac</td><td>purple</td><td><b>มี protein</b></td></tr><tr><td>Ethanol emulsion</td><td>cloudy white</td><td>cloudy white</td><td><b>มี lipid</b></td></tr></table></div>"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:T6,d:2,
 q:`Why does the rate of an enzyme-controlled reaction fall sharply above the optimum temperature?`,
 th:`ทำไมอัตราการเกิดปฏิกิริยาที่มีเอนไซม์ควบคุมจึงลดลงอย่างรวดเร็วเมื่ออุณหภูมิสูงกว่าจุดเหมาะสม`,
 o:[`The enzyme is killed because it is a living organism`,`The substrate molecules move too slowly`,`The enzyme is used up in the reaction`,`The shape of the active site changes (denaturation), so the substrate no longer fits`],
 a:3,
 s:[["กลไก","อุณหภูมิสูงทำให้พันธะที่ยึดโครงสร้าง 3 มิติของโปรตีนแตก → <span class='key'>active site เปลี่ยนรูปร่าง</span> → substrate ไม่เข้าคู่ (not complementary) → สร้าง enzyme-substrate complex ไม่ได้ → เอนไซม์ <b>denatured</b>"],
    ["ตัดตัวเลือก","A: เอนไซม์เป็นโปรตีน ไม่ใช่สิ่งมีชีวิต ห้ามเขียนว่า \"killed\"; B: อุณหภูมิสูงอนุภาคเคลื่อน<b>เร็วขึ้น</b>; C: เอนไซม์เป็นตัวเร่ง ไม่ถูกใช้หมด"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:T6,d:2,
 q:`Why does the activity of amylase increase as temperature rises from 10 °C to 35 °C?`,
 th:`ทำไมกิจกรรมของอะไมเลสจึงเพิ่มขึ้นเมื่ออุณหภูมิเพิ่มจาก 10 °C เป็น 35 °C`,
 o:[`Molecules gain kinetic energy, so enzyme and substrate collide more often and form more enzyme–substrate complexes`,`The active site becomes larger so more substrate fits`,`More amylase is produced by the enzyme`,`The starch becomes denatured and easier to break`],
 a:0,
 s:[["หลักการ","ต่ำกว่า optimum: อุณหภูมิ ↑ → <span class='key'>kinetic energy ↑</span> → เอนไซม์และ substrate ชนกันบ่อยขึ้น → เกิด <b>enzyme–substrate complex</b> มากขึ้นต่อหน่วยเวลา → อัตรา ↑"],
    ["ตัดตัวเลือก","B: active site ไม่ขยาย; C: เอนไซม์สร้างเอนไซม์ไม่ได้; D: starch ไม่ใช่โปรตีน คำว่า denature ใช้กับโปรตีน"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

/* ---------- 7. Nutrition ---------- */
{t:T7,d:1,
 q:`Which word equation represents photosynthesis?`,
 th:`สมการข้อใดแสดงการสังเคราะห์ด้วยแสง`,
 o:[`glucose + oxygen → carbon dioxide + water`,`oxygen + water → glucose + carbon dioxide`,`carbon dioxide + water → glucose + oxygen`,`carbon dioxide + oxygen → glucose + water`],
 a:2,
 s:[["สมการ","<span class='key'>carbon dioxide + water → glucose + oxygen</span> (ต้องมี light และ chlorophyll)<br>6CO<sub>2</sub> + 6H<sub>2</sub>O → C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + 6O<sub>2</sub>"],
    ["สังเกต","เป็นสมการกลับด้านของ aerobic respiration (ตัวเลือก A)"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:T7,d:2,
 q:`When testing a leaf for starch, why is the leaf placed in hot ethanol?`,
 th:`ในการทดสอบแป้งในใบ ทำไมต้องนำใบไปแช่ในเอทานอลร้อน`,
 o:[`To kill the cells and stop chemical reactions`,`To remove chlorophyll so the colour change with iodine can be seen`,`To soften the leaf so iodine can enter`,`To convert glucose into starch`],
 a:1,
 s:[["ขั้นตอนการทดสอบ","<ol><li>ต้มใบในน้ำเดือด ~1 นาที → <b>ฆ่าเซลล์ หยุดปฏิกิริยา</b> และทำลายเยื่อหุ้มเซลล์</li><li>แช่ใน<span class='key'>เอทานอลร้อน</span> (อุ่นในอ่างน้ำร้อน ห้ามใช้เปลวไฟเพราะติดไฟง่าย) → <b>สกัดคลอโรฟิลล์ออก</b> ใบซีด</li><li>จุ่มน้ำอุ่น → ทำให้ใบนิ่ม (เอทานอลทำให้ใบเปราะ)</li><li>หยดไอโอดีน → มีแป้งเป็น blue-black</li></ol>"],
    ["ตัดตัวเลือก","A เป็นหน้าที่ของน้ำเดือด; C เป็นหน้าที่ของการจุ่มน้ำอุ่น"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:T7,d:2,
 q:`A variegated leaf (green and white areas) was kept in light and then tested with iodine. Only the green areas turned blue-black. What does this show?`,
 th:`ใบด่าง (มีส่วนเขียวและส่วนขาว) ได้รับแสงแล้วนำมาทดสอบด้วยไอโอดีน พบว่าเฉพาะส่วนสีเขียวเปลี่ยนเป็นสีน้ำเงินดำ ผลนี้แสดงว่าอะไร`,
 o:[`Light is needed for photosynthesis`,`Carbon dioxide is needed for photosynthesis`,`Oxygen is produced in photosynthesis`,`Chlorophyll is needed for photosynthesis`],
 a:3,
 s:[["วิเคราะห์ตัวแปร","ทั้งส่วนเขียวและขาวได้รับ<b>แสงและ CO<sub>2</sub> เท่ากัน</b> ความแตกต่างเดียวคือ<span class='key'>คลอโรฟิลล์</span> (ส่วนขาวไม่มี)"],
    ["แปลผล","ส่วนเขียว blue-black = มีแป้ง = สังเคราะห์ด้วยแสงได้; ส่วนขาวสีส้มน้ำตาล = ไม่มีแป้ง"],
    ["หมายเหตุ","ก่อนทดลองต้อง <b>destarch</b> ต้นไม้ (เก็บในที่มืด 48 ชม.) เพื่อให้แน่ใจว่าแป้งที่พบเกิดขึ้นระหว่างการทดลอง ✅ <b>คำตอบ D</b>"]]},

{t:T7,d:3,
 q:`The graph of rate of photosynthesis against light intensity rises and then levels off. At light intensities on the flat part of the graph, what is most likely limiting the rate?`,
 th:`กราฟอัตราการสังเคราะห์ด้วยแสงเทียบกับความเข้มแสงเพิ่มขึ้นแล้วคงที่ ที่ความเข้มแสงในช่วงที่กราฟคงที่ ปัจจัยใดน่าจะจำกัดอัตรามากที่สุด`,
 o:[`Carbon dioxide concentration or temperature`,`Light intensity`,`The amount of oxygen in the air`,`The number of stomata closing`],
 a:0,
 s:[["แนวคิด limiting factor","<b>Limiting factor</b> คือปัจจัยที่มีน้อยที่สุดเมื่อเทียบกับความต้องการ และเป็นตัวกำหนดอัตรา"],
    ["อ่านกราฟ","<ul><li>ช่วงกราฟ<b>ชันขึ้น</b>: เพิ่มแสงแล้วอัตราเพิ่ม → แสงเป็น limiting factor</li><li>ช่วง<b>ราบ</b>: เพิ่มแสงแล้วอัตราไม่เพิ่ม → แสง<b>ไม่ใช่</b> limiting factor แล้ว ปัจจัยอื่นคือ <span class='key'>CO<sub>2</sub> concentration หรือ temperature</span></li></ul>"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:T7,d:2,
 q:`A plant grown in soil lacking one mineral ion has yellow leaves because it cannot make enough chlorophyll. Which ion is missing?`,
 th:`พืชที่ปลูกในดินซึ่งขาดแร่ธาตุชนิดหนึ่งมีใบเหลือง เพราะสร้างคลอโรฟิลล์ได้ไม่พอ ขาดไอออนใด`,
 o:[`Nitrate`,`Phosphate`,`Magnesium`,`Calcium`],
 a:2,
 s:[["หน้าที่แร่ธาตุ","<ul><li><span class='key'>Magnesium (Mg<sup>2+</sup>)</span> → เป็นส่วนประกอบของ<b>คลอโรฟิลล์</b> ขาดแล้วใบเหลือง (chlorosis)</li><li><b>Nitrate</b> → สร้าง amino acids/โปรตีน ขาดแล้วต้นแคระ ใบล่างเหลือง</li></ul>"],
    ["หมายเหตุ","ตามหลักสูตร IGCSE ต้องรู้ nitrate และ magnesium เป็นหลัก คำถามเจาะจง \"สร้างคลอโรฟิลล์ไม่ได้\" จึงเป็น Mg"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:T7,d:2,
 q:`Which statement about bile is correct?`,
 th:`ข้อความใดเกี่ยวกับน้ำดีถูกต้อง`,
 o:[`It is made in the gall bladder and digests fat into fatty acids and glycerol`,`It is made in the liver, stored in the gall bladder, emulsifies fats and neutralises stomach acid`,`It is made in the pancreas and contains lipase`,`It is made in the stomach and kills bacteria`],
 a:1,
 s:[["ข้อเท็จจริงเรื่องน้ำดี","<ul><li>สร้างที่<span class='key'>ตับ (liver)</span> เก็บที่<b>ถุงน้ำดี (gall bladder)</b> ปล่อยสู่ duodenum</li><li><b>Emulsifies fat</b>: แตกหยดไขมันใหญ่เป็นหยดเล็ก → เพิ่มพื้นที่ผิวให้ lipase ทำงาน (เป็นการย่อยเชิงกล ไม่ใช่เคมี)</li><li><b>เป็นด่าง</b> → ปรับกรดจากกระเพาะให้เป็นกลาง เหมาะกับเอนไซม์ในลำไส้เล็ก</li></ul>"],
    ["ตัดตัวเลือก","A: น้ำดีไม่ใช่เอนไซม์ ไม่ได้ย่อยไขมันทางเคมี; C: lipase มาจากตับอ่อน; D: กรดในกระเพาะคือ HCl"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:T7,d:2,
 q:`What is the function of the lacteal in a villus?`,
 th:`แลคเทียล (lacteal) ในวิลลัสทำหน้าที่อะไร`,
 o:[`To absorb glucose into the blood`,`To secrete digestive enzymes`,`To increase the surface area of the villus`,`To absorb fatty acids and glycerol into the lymph`],
 a:3,
 s:[["โครงสร้างวิลลัส","<ul><li>Microvilli → เพิ่มพื้นที่ผิว</li><li>ผนังบาง 1 ชั้นเซลล์ → ระยะแพร่สั้น</li><li>เครือข่าย capillaries → ดูด glucose, amino acids และรักษา concentration gradient</li><li><span class='key'>Lacteal</span> (ท่อน้ำเหลือง) → ดูด <b>fatty acids และ glycerol</b></li></ul>"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

/* ---------- 8. Gas exchange ---------- */
{t:T8,d:1,
 q:`Which feature does <b>not</b> help gas exchange in the alveoli?`,
 th:`ลักษณะใด<b>ไม่</b>ช่วยในการแลกเปลี่ยนแก๊สที่ถุงลม`,
 o:[`Thick walls to prevent them from bursting`,`A large total surface area`,`A good blood supply from many capillaries`,`A moist lining`],
 a:0,
 s:[["ลักษณะที่ดีของพื้นผิวแลกเปลี่ยนแก๊ส","<ul><li><b>Large surface area</b> — ถุงลมจำนวนมหาศาล</li><li><span class='key'>Thin walls</span> (หนา 1 เซลล์) — ระยะแพร่สั้น</li><li><b>Good blood supply</b> — รักษา concentration gradient ให้ชัน</li><li><b>Moist</b> — แก๊สละลายก่อนแพร่</li></ul>"],
    ["สรุป","ผนังหนาจะเพิ่มระยะทาง ทำให้แพร่ช้าลง ✅ <b>คำตอบ A</b>"]]},

{t:T8,d:2,
 q:`Which events happen during inhalation (breathing in)?`,
 th:`เหตุการณ์ใดเกิดขึ้นระหว่างการหายใจเข้า`,
 o:[`Diaphragm relaxes and domes upwards; chest volume decreases`,`External intercostal muscles relax; ribs move down and in`,`External intercostal muscles contract; diaphragm contracts and flattens; pressure in the thorax falls`,`Diaphragm contracts; pressure in the thorax rises and air is pushed in`],
 a:2,
 s:[["ลำดับเหตุการณ์","<span class='key'>External intercostals หดตัว</span> → ซี่โครงยกขึ้นและออก + <span class='key'>diaphragm หดตัวแบนลง</span> → ปริมาตรช่องอก ↑ → ความดัน ↓ (ต่ำกว่าบรรยากาศ) → อากาศไหลเข้า"],
    ["ตัดตัวเลือก","A, B = หายใจออก; D: ความดันต้อง<b>ลดลง</b> อากาศจึงไหลเข้า (อากาศไหลจากความดันสูงไปต่ำ)"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:T8,d:2,
 q:`A leaf is sealed in a tube of red hydrogencarbonate indicator and placed in bright light for 2 hours. What colour will the indicator become?`,
 th:`ปิดใบไม้ไว้ในหลอดที่มีสารละลายไฮโดรเจนคาร์บอเนตอินดิเคเตอร์สีแดง วางในที่แสงจ้า 2 ชั่วโมง อินดิเคเตอร์จะเป็นสีใด`,
 o:[`Yellow`,`Purple`,`Orange`,`It stays red`],
 a:1,
 s:[["สีของอินดิเคเตอร์","<ul><li>CO<sub>2</sub> <b>สูง</b> → yellow</li><li>CO<sub>2</sub> ระดับอากาศปกติ → red/orange</li><li>CO<sub>2</sub> <b>ต่ำ</b> → <span class='key'>purple</span></li></ul>"],
    ["วิเคราะห์","แสงจ้า: อัตราการสังเคราะห์ด้วยแสง <b>&gt;</b> อัตราการหายใจ → ใบดูด CO<sub>2</sub> สุทธิ → CO<sub>2</sub> ลดลง → สีม่วง"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:T8,d:2,
 q:`What is the net gas exchange of a leaf kept in complete darkness?`,
 th:`ใบไม้ที่อยู่ในความมืดสนิท มีการแลกเปลี่ยนแก๊สสุทธิเป็นอย่างไร`,
 o:[`Takes in carbon dioxide, releases oxygen`,`No gas exchange occurs`,`Takes in carbon dioxide and oxygen`,`Takes in oxygen, releases carbon dioxide`],
 a:3,
 s:[["หลักการ","ในความมืด<b>ไม่มีการสังเคราะห์ด้วยแสง</b> แต่<span class='key'>respiration เกิดตลอดเวลา</span> (ทั้งกลางวันและกลางคืน)"],
    ["ผล","ใบดูด O<sub>2</sub> เข้าและปล่อย CO<sub>2</sub> ออก ถ้าใช้ hydrogencarbonate indicator จะเปลี่ยนเป็นสีเหลือง"],
    ["เสริม","ที่แสงน้อยระดับหนึ่ง อัตรา photosynthesis = respiration เรียกว่า <b>compensation point</b> ไม่มีการแลกเปลี่ยนแก๊สสุทธิ"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:T8,d:1,
 q:`Which substance in cigarette smoke reduces the oxygen-carrying capacity of the blood?`,
 th:`สารใดในควันบุหรี่ลดความสามารถในการลำเลียงออกซิเจนของเลือด`,
 o:[`Tar`,`Nicotine`,`Carbon monoxide`,`Smoke particles`],
 a:2,
 s:[["ผลของสารในควันบุหรี่","<ul><li><span class='key'>Carbon monoxide</span> → จับกับ haemoglobin แน่นกว่า O<sub>2</sub> (เกิด carboxyhaemoglobin) → เลือดขน O<sub>2</sub> ได้น้อยลง</li><li>Tar → ก่อมะเร็ง (carcinogen) ทำลาย cilia</li><li>Nicotine → เสพติด ทำให้หลอดเลือดหดตัว</li><li>Particles → ระคายเคือง กระตุ้นเมือก</li></ul>"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

/* ---------- 9. CORMMSS & practical skills ---------- */
{t:T9,d:2,
 q:`A student investigates the effect of temperature on the germination of cress seeds. Using CORMMSS, which would be the <b>S (standards / control variables)</b>?`,
 th:`นักเรียนศึกษาผลของอุณหภูมิต่อการงอกของเมล็ดผักสลัดน้ำ (cress) ตามกรอบ CORMMSS ข้อใดคือ <b>S (standards / ตัวแปรควบคุม)</b>`,
 o:[`Temperature`,`The number of seeds that germinate`,`Volume of water and light intensity`,`Repeating the experiment three times`],
 a:2,
 s:[["ทบทวน CORMMSS","<ul><li><b>C</b>onditions = ตัวแปรต้น (อุณหภูมิ)</li><li><b>O</b>rganisms = ชนิด/อายุ/ขนาดเมล็ดเท่ากัน</li><li><b>R</b>epeat = ทำซ้ำ หาค่าเฉลี่ย</li><li><b>M1</b> = วัดอะไร/อย่างไร (นับเมล็ดที่งอก)</li><li><b>M2</b> = วัดนานเท่าไร (เช่น 5 วัน)</li><li><b>S1, S2</b> = <span class='key'>ตัวแปรควบคุม</span></li></ul>"],
    ["ตัดตัวเลือก","A = C; B = M1; D = R"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:T9,d:1,
 q:`In an investigation of the effect of light intensity on photosynthesis in pondweed, the number of oxygen bubbles released per minute is counted. What is the <b>dependent</b> variable?`,
 th:`ในการศึกษาผลของความเข้มแสงต่อการสังเคราะห์ด้วยแสงของสาหร่ายน้ำ นับจำนวนฟองออกซิเจนต่อนาที ตัวแปร<b>ตาม</b>คืออะไร`,
 o:[`Light intensity`,`Number of bubbles released per minute`,`Temperature of the water`,`Type of pondweed`],
 a:1,
 s:[["นิยาม","<ul><li><b>Independent</b> (ตัวแปรต้น) = สิ่งที่เราเปลี่ยน → ความเข้มแสง (แกน x)</li><li><span class='key'>Dependent</span> (ตัวแปรตาม) = สิ่งที่วัด → จำนวนฟองต่อนาที (แกน y)</li><li><b>Control</b> = สิ่งที่คงที่ → อุณหภูมิ, ชนิดสาหร่าย, CO<sub>2</sub></li></ul>"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:T9,d:2,
 q:`Using the SLAP framework for drawing graphs, which practice would <b>lose</b> marks?`,
 th:`ตามหลัก SLAP ในการเขียนกราฟ ข้อใดจะทำให้<b>เสียคะแนน</b>`,
 o:[`Using a scale that goes 0, 3, 6, 9 on the y-axis`,`Labelling each axis with the variable and its unit, e.g. Time / minutes`,`Plotting points with small crosses using a sharp pencil`,`Choosing a scale so the plotted points cover more than half of the grid`],
 a:0,
 s:[["SLAP","<ul><li><b>S</b>cale — ช่วงสม่ำเสมอ ใช้ง่าย (1, 2, 5, 10) และใช้พื้นที่กราฟ ≥ 50%</li><li><b>L</b>ine — เส้นตรงหรือเส้นโค้งเรียบ/เชื่อมจุดด้วยไม้บรรทัด ไม่ลากเกินข้อมูล</li><li><b>A</b>xes — ตัวแปรต้นแกน x ตัวแปรตามแกน y ใส่ชื่อและหน่วย</li><li><b>P</b>lots — จุดแม่นยำ ใช้ × หรือ ⊙ เล็ก ๆ</li></ul>"],
    ["วิเคราะห์","ช่วง 0, 3, 6, 9 เป็น <span class='key'>awkward scale</span> ทำให้ plot และอ่านค่าผิดง่าย"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]}
];

const written = [
{t:T9,m:6,
 q:`Some species of seed will only germinate after they have been exposed to light.<br>Design an investigation to determine if exposure to light affects germination.<br>Include experimental details in your answer and write in full sentences.`,
 th:`เมล็ดบางชนิดงอกได้ก็ต่อเมื่อได้รับแสง จงออกแบบการทดลองเพื่อหาว่าการได้รับแสงมีผลต่อการงอกหรือไม่ ให้รายละเอียดการทดลองและเขียนเป็นประโยคเต็ม`,
 ms:[`<b>C</b> – Expose one group of seeds to light and keep another group in the dark (e.g. cover dish with foil / black box)`,
     `<b>O</b> – Use seeds of the same species (same age / size / batch)`,
     `<b>R</b> – Use several seeds per dish (e.g. 20) and repeat each condition (e.g. 3 dishes) to calculate a mean`,
     `<b>M1</b> – Count the number (or percentage) of seeds that germinate, e.g. radicle visible`,
     `<b>M2</b> – After a stated time, e.g. 5 days`,
     `<b>S1</b> – Keep temperature the same (e.g. 25 °C incubator)`,
     `<b>S2</b> – Keep volume of water / type of substrate (cotton wool) / oxygen the same`],
 ans:`<p>I will place 20 seeds of the same species and the same age on damp cotton wool in each of six Petri dishes. Three dishes will be kept in the light and three dishes will be wrapped in aluminium foil so that they are kept in the dark. All dishes will be kept in an incubator at 25 °C and each will be given the same volume of water, 10 cm³. After 5 days I will count the number of seeds that have germinated (a radicle is visible) in each dish and calculate the mean percentage germination for light and dark.</p>`,
 tip:`โจทย์ 6 คะแนน = ต้องมีอย่างน้อย 6 จุดจาก CORMMSS (มี 7 จุดให้เลือก) และต้องเขียนเป็น<b>ประโยคเต็ม</b> ไม่ใช่ bullet ห้ามลืม M2 (ระยะเวลา) ซึ่งนักเรียนลืมบ่อยที่สุด`},

{t:T4,m:3,
 q:`A student uses a respirometer to measure the oxygen absorbed by germinating seeds. The coloured liquid moves a distance of <b>6.0 mm</b>. The diameter of the tube is <b>1.0 mm</b>.<br>Calculate the volume of oxygen absorbed using the formula: volume = π × radius² × distance. Give your answer in cm³. (π = 3.14)`,
 th:`นักเรียนใช้ respirometer วัด O<sub>2</sub> ที่เมล็ดกำลังงอกดูดไป หยดของเหลวสีเคลื่อนไป 6.0 mm หลอดมีเส้นผ่านศูนย์กลาง 1.0 mm จงคำนวณปริมาตร O<sub>2</sub> ที่ถูกดูดไป (หน่วย cm³)`,
 ms:[`Radius = 1.0 ÷ 2 = 0.5 mm`,
     `Volume = 3.14 × 0.5² × 6.0 = 4.71 mm³`,
     `Converted to cm³: 4.71 ÷ 1000 = 0.00471 cm³ (≈ 0.0047 cm³)`],
 ans:`<p>r = 0.5 mm<br>V = π r² d = 3.14 × 0.25 × 6.0 = 4.71 mm³<br>V = 4.71 ÷ 1000 = <b>0.00471 cm³</b></p>`,
 tip:`กับดัก 2 จุด: (1) โจทย์ให้ <b>diameter</b> ต้องหารสองก่อน (2) 1 cm³ = 1000 mm³ ไม่ใช่ 10 หรือ 100`},

{t:T4,m:4,
 q:`The table shows the rate of oxygen absorption by germinating seeds at two temperatures.
 <div class='tbl'><table><tr><th>Temperature / °C</th><th>Rate of oxygen absorption / mm³ per hour</th></tr><tr><td>12</td><td>0.8</td></tr><tr><td>22</td><td>1.4</td></tr></table></div>
 (a) Calculate the percentage increase in the rate of oxygen absorption at 22 °C compared with 12 °C. [2]<br>(b) Suggest why the rate of oxygen absorption is greater at 22 °C than at 12 °C. [2]`,
 th:`(a) คำนวณร้อยละที่อัตราการดูด O<sub>2</sub> ที่ 22 °C เพิ่มขึ้นเมื่อเทียบกับ 12 °C (b) เสนอเหตุผลว่าทำไมอัตราที่ 22 °C สูงกว่า`,
 ms:[`(a) Increase = 1.4 − 0.8 = 0.6`,
     `(a) % increase = 0.6 ÷ 0.8 × 100 = 75 %`,
     `(b) Enzymes (for respiration) are more active / more kinetic energy / more enzyme–substrate collisions at 22 °C`,
     `(b) So the rate of aerobic respiration increases and more oxygen is used`],
 ans:`<p>(a) (1.4 − 0.8) ÷ 0.8 × 100 = <b>75 %</b></p><p>(b) At 22 °C the molecules have more kinetic energy, so respiratory enzymes and substrates collide more often and more enzyme–substrate complexes form. The rate of aerobic respiration increases, so the seeds use oxygen faster.</p>`,
 tip:`สูตร % change = (ค่าใหม่ − ค่าเดิม) ÷ <b>ค่าเดิม</b> × 100 — ส่วนต้องเป็นค่าเริ่มต้น (12 °C) ไม่ใช่ 1.4`},

{t:T5,m:4,
 q:`A plant cell is placed in distilled water and another identical plant cell is placed in a concentrated solution of sodium chloride.<br>Explain the differences in the appearance of the cell in distilled water and the cell in the concentrated sodium chloride solution.`,
 th:`เซลล์พืชหนึ่งแช่ในน้ำกลั่น อีกเซลล์หนึ่งแช่ในสารละลายโซเดียมคลอไรด์เข้มข้น จงอธิบายความแตกต่างของลักษณะเซลล์ทั้งสอง`,
 ms:[`In distilled water, water enters the cell by osmosis (higher water potential outside)`,
     `The vacuole enlarges and the cell becomes turgid; the cell wall prevents it from bursting`,
     `In sodium chloride, water leaves the cell by osmosis (lower water potential outside)`,
     `The vacuole / cytoplasm shrinks and the membrane pulls away from the cell wall (plasmolysis)`,
     `Osmosis occurs through the partially permeable cell membrane`],
 ans:`<p>In distilled water, the water potential outside the cell is higher than inside, so water moves into the cell by osmosis through the partially permeable membrane. The vacuole swells and pushes the cytoplasm against the cell wall, so the cell becomes turgid; the cell wall stops it from bursting.</p><p>In concentrated sodium chloride solution, the water potential outside is lower, so water moves out of the cell by osmosis. The vacuole and cytoplasm shrink and the cell membrane pulls away from the cell wall, so the cell is plasmolysed.</p>`,
 tip:`โจทย์ <b>Explain</b> ต้องบอก <b>WHY</b> (ทิศทางของ water potential/osmosis) ไม่ใช่แค่ describe ว่าเซลล์ "บวม" หรือ "หด" และช่องว่างระหว่างผนังกับเยื่อหุ้ม (O) บรรจุสารละลายโซเดียมคลอไรด์`},

{t:T3,m:3,
 q:`A student draws a cheek cell seen under a light microscope. The drawing of the cell is <b>60 mm</b> wide. The magnification of the drawing is <b>×400</b>.<br>Calculate the actual width of the cell in micrometres (µm). Show your working.`,
 th:`นักเรียนวาดภาพเซลล์เยื่อบุกระพุ้งแก้มที่เห็นในกล้องจุลทรรศน์ ภาพวาดกว้าง 60 mm กำลังขยาย ×400 จงคำนวณความกว้างจริงของเซลล์ในหน่วยไมโครเมตร`,
 ms:[`Actual size = image size ÷ magnification`,
     `60 ÷ 400 = 0.15 mm`,
     `0.15 × 1000 = 150 µm`],
 ans:`<p>Actual size = image ÷ magnification = 60 mm ÷ 400 = 0.15 mm<br>0.15 mm × 1000 = <b>150 µm</b></p>`,
 tip:`จำสามเหลี่ยม <b>I = A × M</b> และ 1 mm = 1000 µm ตรวจสอบความสมเหตุสมผล: เซลล์สัตว์ทั่วไปมีขนาด 10–100+ µm`},

{t:T3,m:4,
 q:`Two agar cubes containing pink phenolphthalein are placed in acid. Cube X has sides of 1 cm; cube Y has sides of 2 cm.<br>(a) Calculate the surface area to volume ratio of each cube. [2]<br>(b) Explain which cube will become completely colourless first. [2]`,
 th:`ก้อนวุ้นที่มี phenolphthalein สีชมพู 2 ก้อน แช่ในกรด ก้อน X ด้านยาว 1 cm ก้อน Y ด้านยาว 2 cm (a) คำนวณ SA:V ของแต่ละก้อน (b) อธิบายว่าก้อนใดจะไม่มีสีทั้งก้อนก่อน`,
 ms:[`X: SA = 6 cm², V = 1 cm³ → 6 : 1`,
     `Y: SA = 24 cm², V = 8 cm³ → 3 : 1`,
     `Cube X becomes colourless first because it has a larger surface area to volume ratio`,
     `Acid has a shorter distance to diffuse to the centre of X (0.5 cm vs 1 cm)`],
 ans:`<p>(a) X: SA = 6 × 1² = 6 cm², V = 1³ = 1 cm³, SA:V = <b>6 : 1</b>. Y: SA = 6 × 2² = 24 cm², V = 2³ = 8 cm³, SA:V = <b>3 : 1</b>.</p><p>(b) Cube X, because it has a larger surface area to volume ratio, so more acid can diffuse in per unit volume, and the distance from the surface to the centre is shorter (0.5 cm instead of 1 cm).</p>`,
 tip:`เชื่อมโยงกับชีววิทยาจริง: สิ่งมีชีวิตขนาดใหญ่มี SA:V ต่ำ การแพร่ผ่านผิวกายไม่พอ จึงต้องมีพื้นผิวแลกเปลี่ยนเฉพาะ (ปอด, วิลลัส) และระบบหมุนเวียน`},

{t:T6,m:5,
 q:`Describe how you would test a sample of food to find out whether it contains (a) reducing sugar and (b) protein. Include the reagents used and the positive results.`,
 th:`อธิบายวิธีทดสอบตัวอย่างอาหารว่ามี (a) น้ำตาลรีดิวซ์ และ (b) โปรตีน หรือไม่ ระบุสารที่ใช้และผลบวก`,
 ms:[`Grind/crush the food and mix with water (make a solution/suspension)`,
     `Reducing sugar: add (equal volume of) Benedict's solution`,
     `Heat in a (hot) water bath, e.g. 80 °C for 5 minutes`,
     `Positive: blue → green/yellow/orange/brick-red (precipitate)`,
     `Protein: add biuret reagent (sodium hydroxide + copper sulfate)`,
     `Positive: blue → purple / lilac (no heating needed)`],
 ans:`<p>First, crush the food and mix it with distilled water in a test tube.</p><p>(a) Add an equal volume of Benedict's solution and heat the tube in a water bath at about 80 °C for 5 minutes. If reducing sugar is present, the colour changes from blue to green, yellow, orange or brick red, depending on the amount.</p><p>(b) Add biuret reagent (or sodium hydroxide followed by a few drops of dilute copper sulfate) and shake. If protein is present the colour changes from blue to purple (lilac).</p>`,
 tip:`ความปลอดภัย: ใช้ <b>water bath</b> ไม่ต้มโดยตรงบนเปลวไฟ และสวมแว่นตา — Benedict's ต้องให้ความร้อน แต่ biuret ไม่ต้อง`},

{t:T9,m:6,
 q:`Describe an experiment you could carry out to determine the effect of pH on the rate of digestion of starch by amylase.<br>Your answer should include experimental details and be written in full sentences.`,
 th:`อธิบายการทดลองเพื่อหาผลของ pH ต่ออัตราการย่อยแป้งโดยอะไมเลส ให้รายละเอียดการทดลองและเขียนเป็นประโยคเต็ม`,
 ms:[`<b>C</b> – Use buffer solutions of different pH, e.g. pH 4, 5, 6, 7, 8`,
     `<b>O</b> – Use the same amylase (same source/concentration) and same starch solution`,
     `<b>R</b> – Repeat each pH three times and calculate a mean`,
     `<b>M1</b> – Take samples every 30 s and add to iodine on a spotting tile; record time until iodine stays orange-brown (no starch)`,
     `<b>M2</b> – Continue for a stated maximum time, e.g. up to 10 minutes; rate = 1 ÷ time`,
     `<b>S1</b> – Keep temperature constant using a water bath, e.g. 37 °C`,
     `<b>S2</b> – Keep volumes/concentrations of starch and amylase the same`],
 ans:`<p>I will put 5 cm³ of 1 % starch solution and 1 cm³ of pH buffer into a test tube, using buffers of pH 4, 5, 6, 7 and 8. The tubes and a separate tube of 1 % amylase solution will be placed in a water bath at 37 °C for 5 minutes to reach the same temperature. I will add 2 cm³ of the same amylase solution to each tube and start a stopwatch. Every 30 seconds I will put a drop of the mixture onto iodine solution on a spotting tile, and record the time when the iodine no longer turns blue-black, up to a maximum of 10 minutes. I will repeat each pH three times, calculate the mean time and work out the rate as 1 ÷ time.</p>`,
 tip:`ข้อนี้ \"C\" คือ pH ต้องควบคุมด้วย <b>buffer</b> และต้องบอกวิธีวัด (iodine + spotting tile) ให้ชัดเจน`},

{t:T8,m:4,
 q:`Explain how the alveoli are adapted for efficient gas exchange.`,
 th:`อธิบายว่าถุงลมปรับตัวอย่างไรเพื่อให้แลกเปลี่ยนแก๊สได้อย่างมีประสิทธิภาพ`,
 ms:[`Many alveoli give a large surface area, so more gas diffuses at once`,
     `Walls are thin (one cell thick) / close to capillaries, so the diffusion distance is short`,
     `Rich blood supply (many capillaries) maintains a steep concentration gradient`,
     `Ventilation brings fresh air in and removes CO<sub>2</sub>, maintaining the gradient`,
     `Moist lining lets gases dissolve before diffusing`],
 ans:`<p>There are millions of alveoli, which give a very large surface area for diffusion. The alveolus wall and the capillary wall are each only one cell thick, so the diffusion distance for oxygen and carbon dioxide is short. Each alveolus is surrounded by many capillaries, and blood flow carries oxygen away and brings carbon dioxide, which maintains a steep concentration gradient. Breathing also replaces the air in the alveoli. The inner surface is moist so gases can dissolve before they diffuse.</p>`,
 tip:`โจทย์ Explain: ทุกลักษณะต้องตามด้วย \"so…\" บอกว่าช่วยการแพร่อย่างไร เช่น thin wall <b>so</b> short diffusion distance`},

{t:T9,m:5,
 q:`Probiotic drinks contain living microorganisms. Scientists gave hospital patients who were taking antibiotics either a probiotic drink or a drink with no microorganisms (control group).
 <div class='tbl'><table><tr><th>Group</th><th>Number of patients</th><th>Developed diarrhoea / %</th><th><i>Clostridium difficile</i> in faeces / %</th></tr><tr><td>Probiotic drink</td><td>69</td><td>12</td><td>0</td></tr><tr><td>Control</td><td>66</td><td>34</td><td>17</td></tr></table></div>
 (a) Give the meaning of the term <i>control group</i>. [1]<br>(b) Discuss whether the results show links between having a probiotic drink and the likelihood of developing diarrhoea or having <i>Clostridium difficile</i> in the faeces. Use information from the table and your own knowledge. [4]`,
 th:`(a) ให้ความหมายของ control group (b) อภิปรายว่าผลการทดลองแสดงความเชื่อมโยงระหว่างการดื่มโพรไบโอติกกับโอกาสเกิดท้องร่วงหรือพบ <i>C. difficile</i> ในอุจจาระหรือไม่ ใช้ข้อมูลในตารางและความรู้ของตนเอง`,
 ms:[`(a) A group treated the same in every way but not given the probiotic, used for comparison`,
     `Probiotic group had less diarrhoea: 12 % vs 34 % (about one-third)`,
     `No <i>C. difficile</i> in the probiotic group vs 17 % in control, so probiotic may prevent growth of the pathogen`,
     `Suggested reason: antibiotics kill normal gut bacteria; probiotic bacteria replace them / compete with <i>C. difficile</i>`,
     `Limitation: small sample / only one study / correlation not proof / other factors (age, diet, type of antibiotic) not stated / not repeated`],
 ans:`<p>(a) A control group is a group of patients treated in exactly the same way but not given the probiotic, so the results can be compared to see the effect of the probiotic.</p><p>(b) The results suggest a link. Fewer patients who had the probiotic drink developed diarrhoea (12 %) than in the control group (34 %), about three times fewer. No patients in the probiotic group had <i>C. difficile</i> in their faeces, compared with 17 % in the control. This could be because antibiotics kill the normal gut bacteria, and the probiotic microorganisms replace them and compete with <i>C. difficile</i>. However, the sample size is small (fewer than 70 patients per group), it is only one study, and other factors such as age, diet or type of antibiotic may not have been controlled, so it does not prove that probiotics cause the reduction.</p>`,
 tip:`โจทย์ <b>Discuss</b> ต้องมีทั้งสองด้าน: หลักฐานสนับสนุน (อ้างตัวเลขจากตาราง) + ข้อจำกัด (sample size, ตัวแปรที่ไม่ได้ควบคุม, correlation ≠ causation)`}
];

window.EXAMS.bio = {
  title:"Biology", code:"IGCSE Biology · Mock Paper 1",
  topics:["Characteristics & variety of living organisms","Cells, levels of organisation, magnification","Respiration & respirometer","Movement in & out of cells","Biological molecules & food tests","Nutrition, gas exchange, CORMMSS"],
  mcq, written
};
})();
