window.EXAMS = window.EXAMS || {};
(function(){
const H1="Cell Structure & Organisation", H2="Molecular Genetics", H3="Protein Transport & Endomembrane",
      H4="Passive Transport", H5="Active Transport", H6="Carbohydrates, Lipids & Proteins", H7="Enzymes & Inhibitors";

const mcq = [
/* ---------- Cell structure & organisation ---------- */
{t:H1,d:1,
 q:`What is the main function of the Golgi apparatus?`,
 th:`หน้าที่หลักของกอลจิแอปพาราตัสคืออะไร`,
 o:[`Releasing energy by aerobic respiration`,`Synthesising proteins from amino acids`,`Modifying, sorting and packaging proteins into vesicles`,`Storing the genetic information of the cell`],
 a:2,
 s:[["หน้าที่ Golgi","<ul><li><b>Modify</b> — เติมน้ำตาลหรือสารเคมีอื่นให้โปรตีน (เช่น สร้าง glycoprotein)</li><li><b>Sort</b> — คัดแยกโมเลกุลตามปลายทาง</li><li><b>Package</b> — บรรจุลง <span class='key'>vesicles</span> เพื่อส่งภายในเซลล์หรือหลั่งออกนอกเซลล์</li></ul>"],
    ["ตัดตัวเลือก","A = mitochondrion; B = ribosome; D = nucleus"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:H1,d:2,
 q:`Which part of the Golgi apparatus receives vesicles arriving from the endoplasmic reticulum?`,
 th:`ส่วนใดของกอลจิแอปพาราตัสรับเวสิเคิลที่มาจากร่างแหเอนโดพลาซึม`,
 o:[`The cis face`,`The trans face`,`The nuclear pore`,`The lysosome`],
 a:0,
 s:[["โครงสร้าง Golgi","ประกอบด้วย <b>cisternae</b> (ถุงเยื่อแบนซ้อนกันเหมือนแพนเค้ก) มีสองด้าน:"],
    ["cis vs trans","<ul><li><span class='key'>Cis face</span> = ด้าน<b>รับ</b> (receiving) หันเข้าหาใจกลางเซลล์และ ER</li><li><span class='key'>Trans face</span> = ด้าน<b>ส่งออก</b> (shipping) หันไปทาง cell membrane</li></ul>ช่วยจำ: <b>c</b>is = <b>c</b>ome in, <b>t</b>rans = <b>t</b>ransport out"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:H1,d:1,
 q:`Which statement describes the rough endoplasmic reticulum?`,
 th:`ข้อความใดอธิบายร่างแหเอนโดพลาซึมชนิดผิวขรุขระ (rough ER) ได้ถูกต้อง`,
 o:[`A double membrane organelle where aerobic respiration takes place`,`A network of membranes covered with ribosomes; its spaces transport proteins through the cell`,`A stack of flattened sacs that packages proteins`,`A bag of digestive enzymes`],
 a:1,
 s:[["นิยาม","<span class='key'>Rough ER</span> = เครือข่ายเยื่อที่มี <b>ribosomes</b> เกาะ (จึงดูขรุขระ) ช่องว่างระหว่างเยื่อ (lumen) เป็นระบบ<b>ขนส่งโปรตีน</b>ไปยังส่วนต่าง ๆ ของเซลล์"],
    ["ตัดตัวเลือก","A = mitochondrion; C = Golgi; D = lysosome"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:H1,d:1,
 q:`How many chromosomes are found in the nucleus of a normal human body cell?`,
 th:`นิวเคลียสของเซลล์ร่างกายปกติของมนุษย์มีโครโมโซมกี่แท่ง`,
 o:[`23`,`23 pairs plus one`,`92`,`46 (23 pairs)`],
 a:3,
 s:[["ข้อเท็จจริง","เซลล์ร่างกาย (body/somatic cell) มี <span class='key'>46 โครโมโซม = 23 คู่</span> (diploid) ได้จากพ่อ 23 และแม่ 23"],
    ["เปรียบเทียบ","เซลล์สืบพันธุ์ (sperm, egg) มี 23 แท่ง (haploid); 92 คือจำนวนหลังจำลอง DNA แล้วนับเป็นโครมาทิด"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:H1,d:1,
 q:`Which of the following is a <b>tissue</b>?`,
 th:`ข้อใดเป็น<b>เนื้อเยื่อ (tissue)</b>`,
 o:[`Heart`,`Epithelium`,`Digestive system`,`Neurone`],
 a:1,
 s:[["ระดับการจัดระบบ","<ul><li>Neurone = <b>cell</b></li><li><span class='key'>Epithelium</span> = <b>tissue</b> (กลุ่มเซลล์คล้ายกันทำงานร่วมกัน)</li><li>Heart = <b>organ</b> (มีเนื้อเยื่อกล้ามเนื้อ, connective, nerve, epithelium)</li><li>Digestive system = <b>organ system</b></li></ul>"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:H1,d:2,
 q:`Why do muscle cells contain many mitochondria?`,
 th:`ทำไมเซลล์กล้ามเนื้อจึงมีไมโทคอนเดรียจำนวนมาก`,
 o:[`To store glycogen for later use`,`To produce proteins for contraction`,`To release a lot of energy (ATP) by aerobic respiration for contraction`,`To increase the surface area for diffusion`],
 a:2,
 s:[["เชื่อมโครงสร้างกับหน้าที่","Mitochondria เป็นแหล่งของ <span class='key'>aerobic respiration</span> ผลิต <b>ATP</b> การหดตัวของกล้ามเนื้อใช้พลังงานมาก จึงต้องมีไมโทคอนเดรียมาก (เช่นเดียวกับ sperm ที่ต้องว่ายน้ำ)"],
    ["ตัดตัวเลือก","A: glycogen ไม่ได้เก็บในไมโทคอนเดรีย; B: การสร้างโปรตีนเป็นหน้าที่ ribosome; D: ไม่เกี่ยว"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:H1,d:1,
 q:`Which description of the cell (plasma) membrane is correct?`,
 th:`ข้อใดอธิบายเยื่อหุ้มเซลล์ได้ถูกต้อง`,
 o:[`A partially permeable phospholipid bilayer forming a boundary between cytoplasm and the outside`,`A rigid layer of cellulose that prevents bursting`,`A fully permeable layer that lets all substances through`,`A single layer of protein surrounding the nucleus`],
 a:0,
 s:[["โครงสร้าง","Cell membrane = <span class='key'>lipid (phospholipid) bilayer</span> มีโปรตีนแทรก เป็นขอบเขตระหว่าง cytoplasm กับภายนอก"],
    ["สมบัติ","<b>Partially / selectively permeable</b> — ยอมให้บางสารผ่าน ควบคุมการเข้าออก"],
    ["ตัดตัวเลือก","B = cell wall ของพืช (เซลล์คนไม่มี); C: ไม่ใช่ fully permeable; D: ผิด"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:H1,d:3,
 q:`Cells in the pancreas secrete large amounts of digestive enzymes. Which organelles would you expect to be especially abundant in these cells?`,
 th:`เซลล์ในตับอ่อนหลั่งเอนไซม์ย่อยอาหารปริมาณมาก คาดว่าเซลล์นี้จะมีออร์แกเนลล์ใดมากเป็นพิเศษ`,
 o:[`Chloroplasts and cell wall`,`Lysosomes only`,`Large permanent vacuole`,`Rough ER and Golgi apparatus`],
 a:3,
 s:[["วิเคราะห์","เอนไซม์ย่อยอาหาร = <b>โปรตีนที่ถูกหลั่งออกนอกเซลล์</b> (secreted protein)"],
    ["เส้นทาง","ribosome บน <span class='key'>rough ER</span> สังเคราะห์ → vesicle → <span class='key'>Golgi</span> ดัดแปลง บรรจุ → secretory vesicle → exocytosis<br>(และมี mitochondria มากเพื่อให้ ATP)"],
    ["ตัดตัวเลือก","A, C เป็นโครงสร้างของเซลล์พืช; B: lysosome ไม่ได้ทำหน้าที่หลั่งเอนไซม์ออกนอกเซลล์"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

/* ---------- Molecular genetics ---------- */
{t:H2,d:2,
 q:`A sample of double-stranded DNA contains <b>30 % adenine</b>. What percentage of its bases are cytosine?`,
 th:`ตัวอย่าง DNA สายคู่มีเบส<b>อะดีนีน 30 %</b> มีไซโทซีนกี่เปอร์เซ็นต์`,
 o:[`30 %`,`20 %`,`40 %`,`70 %`],
 a:1,
 s:[["กฎการจับคู่เบส","<span class='key'>A คู่กับ T</span>, <span class='key'>C คู่กับ G</span> → ใน DNA สายคู่ %A = %T และ %C = %G"],
    ["คำนวณ","A = 30 % → T = 30 % → A + T = 60 %<br>C + G = 100 − 60 = 40 % → C = 40 ÷ 2 = <b>20 %</b>"],
    ["กับดัก","40 % คือ C + G รวมกัน ไม่ใช่ C อย่างเดียว ✅ <b>คำตอบ B</b>"]]},

{t:H2,d:1,
 q:`Which three components make up a DNA nucleotide?`,
 th:`นิวคลีโอไทด์ของ DNA ประกอบด้วยองค์ประกอบ 3 ส่วนใด`,
 o:[`Ribose, phosphate, amino acid`,`Glucose, phosphate, nitrogenous base`,`Deoxyribose, phosphate, nitrogenous base`,`Deoxyribose, glycerol, fatty acid`],
 a:2,
 s:[["โครงสร้างนิวคลีโอไทด์","<span class='key'>phosphate + deoxyribose sugar + nitrogenous base</span> (A, T, C หรือ G)"],
    ["เสริม","นิวคลีโอไทด์ต่อกันเป็นสายด้วย <b>sugar–phosphate backbone</b> สองสายยึดกันด้วยพันธะไฮโดรเจนระหว่างเบสคู่สม บิดเป็น <b>double helix</b><br>RNA ใช้น้ำตาล <b>ribose</b> (ตัวเลือก A)"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:H2,d:2,
 q:`DNA replication is described as <b>semi-conservative</b>. What does this mean?`,
 th:`การจำลอง DNA เรียกว่าแบบ <b>semi-conservative</b> หมายความว่าอย่างไร`,
 o:[`Each new DNA molecule contains one original strand and one newly made strand`,`One new DNA molecule has both original strands; the other has two new strands`,`Each strand is a random mixture of old and new pieces`,`Only half of the DNA in the nucleus is copied`],
 a:0,
 s:[["กระบวนการ","DNA คลายเกลียว พันธะไฮโดรเจนแยก สองสายเดิมแต่ละสายเป็น<b>แม่แบบ (template)</b> นิวคลีโอไทด์อิสระมาจับคู่แบบ complementary (A–T, C–G) แล้ว DNA polymerase เชื่อมเป็นสายใหม่"],
    ["ความหมาย","ได้ DNA 2 โมเลกุล แต่ละโมเลกุลมี <span class='key'>สายเดิม 1 สาย + สายใหม่ 1 สาย</span> — \"semi\" = ครึ่งหนึ่งถูกอนุรักษ์ไว้"],
    ["ตัดตัวเลือก","B = conservative model; C = dispersive model (ทั้งสองถูกหักล้างโดยการทดลองของ Meselson–Stahl)"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:H2,d:2,
 q:`The template strand of a DNA sequence is <b>TAC GGA</b>. What is the sequence of the mRNA transcribed from it?`,
 th:`สายแม่แบบของ DNA มีลำดับ <b>TAC GGA</b> mRNA ที่ถอดรหัสได้มีลำดับอย่างไร`,
 o:[`ATG CCT`,`TAC GGA`,`UAC GGA`,`AUG CCU`],
 a:3,
 s:[["กฎการจับคู่ใน transcription","DNA → RNA: <b>A → U</b>, <b>T → A</b>, <b>C → G</b>, <b>G → C</b> (RNA ใช้ <span class='key'>uracil แทน thymine</span>)"],
    ["ทำทีละเบส","T→A, A→U, C→G &nbsp;|&nbsp; G→C, G→C, A→U → <b>AUG CCU</b>"],
    ["ตัดตัวเลือก","A: มี T ใน RNA ไม่ได้; B, C: ลอกตามแม่แบบแทนที่จะเป็น complementary"],
    ["เสริม","AUG เป็น start codon (methionine) ✅ <b>คำตอบ D</b>"]]},

{t:H2,d:1,
 q:`Which type of RNA carries a specific amino acid to the ribosome?`,
 th:`RNA ชนิดใดนำกรดอะมิโนที่จำเพาะมายังไรโบโซม`,
 o:[`mRNA`,`tRNA`,`rRNA`,`DNA`],
 a:1,
 s:[["RNA 3 ชนิด","<ul><li><b>mRNA</b> (messenger) — นำรหัสพันธุกรรมจาก DNA ในนิวเคลียสไปยังไรโบโซม</li><li><span class='key'>tRNA</span> (transfer) — นำกรดอะมิโนเฉพาะมายังไรโบโซม โดยมี <b>anticodon</b> จับคู่กับ codon</li><li><b>rRNA</b> (ribosomal) — ส่วนประกอบโครงสร้างของไรโบโซม</li></ul>"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:H2,d:2,
 q:`The coding region of an mRNA molecule is 300 bases long (not including the stop codon). How many amino acids are in the polypeptide it codes for?`,
 th:`ส่วนที่ถอดรหัสของ mRNA ยาว 300 เบส (ไม่นับ stop codon) พอลิเพปไทด์ที่ได้มีกรดอะมิโนกี่ตัว`,
 o:[`900`,`300`,`100`,`150`],
 a:2,
 s:[["หลักการ","รหัสพันธุกรรมเป็น <span class='key'>triplet code</span> — <b>codon</b> 1 ตัว = 3 เบส = กรดอะมิโน 1 ตัว"],
    ["คำนวณ","300 ÷ 3 = <b>100 amino acids</b>"],
    ["ตัวเลือกหลอก","A = คูณ 3 แทนหาร; D = หาร 2 (สับสนกับเบสคู่ของ DNA)"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:H2,d:1,
 q:`Which feature is found in RNA but <b>not</b> in DNA?`,
 th:`ลักษณะใดพบใน RNA แต่<b>ไม่</b>พบใน DNA`,
 o:[`Phosphate groups`,`The base cytosine`,`Two strands forming a double helix`,`The base uracil`],
 a:3,
 s:[["เปรียบเทียบ DNA กับ RNA","<div class='tbl'><table><tr><th></th><th>DNA</th><th>RNA</th></tr><tr><td>จำนวนสาย</td><td>2 (double helix)</td><td>1</td></tr><tr><td>น้ำตาล</td><td>deoxyribose</td><td>ribose</td></tr><tr><td>เบส</td><td>A, T, C, G</td><td>A, <b>U</b>, C, G</td></tr></table></div>"],
    ["ตัดตัวเลือก","A, B มีทั้งคู่; C เป็นของ DNA"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:H2,d:2,
 q:`According to the central dogma (DNA → RNA → protein), why do different people have slightly different proteins?`,
 th:`ตามหลักการ central dogma (DNA → RNA → โปรตีน) ทำไมคนแต่ละคนจึงมีโปรตีนแตกต่างกันเล็กน้อย`,
 o:[`Their DNA base sequences differ, so the mRNA codons and amino acid sequences differ`,`They use different genetic codes`,`Their ribosomes are made of different amino acids`,`Proteins are absorbed from different foods`],
 a:0,
 s:[["Central dogma","DNA —<i>transcription</i>→ mRNA —<i>translation</i>→ โปรตีน ลำดับเบสใน DNA กำหนด<span class='key'>ลำดับกรดอะมิโน</span>"],
    ["เหตุผล","แต่ละคนมี <b>alleles</b> (รูปแบบของยีน) ต่างกัน → ลำดับเบสต่าง → codon ใน mRNA ต่าง → ลำดับกรดอะมิโนต่าง → โปรตีนต่าง (เช่น หมู่เลือด ABO) ยกเว้นฝาแฝดแท้"],
    ["ตัดตัวเลือก","B: รหัสพันธุกรรมเป็น <b>universal</b> ใช้เหมือนกันทุกคน; C ไม่เกี่ยว; D: โปรตีนในอาหารถูกย่อยเป็นกรดอะมิโนก่อน แล้วร่างกายสร้างโปรตีนของตัวเองตาม DNA"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:H2,d:2,
 q:`A DNA sequence changes from <b>ATG CCA TTC</b> to <b>ATG CGA TTC</b>. Which type of mutation is this?`,
 th:`ลำดับ DNA เปลี่ยนจาก <b>ATG CCA TTC</b> เป็น <b>ATG CGA TTC</b> เป็นการกลายพันธุ์ประเภทใด`,
 o:[`Deletion`,`Duplication`,`Substitution`,`Inversion`],
 a:2,
 s:[["เทียบทีละเบส","ATG C<b>C</b>A TTC → ATG C<b>G</b>A TTC — จำนวนเบสเท่าเดิม มีเบส C หนึ่งตัวถูก<b>แทนที่</b>ด้วย G"],
    ["ประเภทการกลายพันธุ์","<ul><li><span class='key'>Substitution</span> — เบสหนึ่งถูกแทนที่</li><li>Deletion — เบสหายไป</li><li>Duplication — ลำดับถูกทำซ้ำ</li><li>Inversion — ลำดับกลับหัว</li></ul>"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:H2,d:3,
 q:`Why is a deletion of one base near the start of a gene usually more harmful than a substitution of one base?`,
 th:`ทำไมการขาดหายของเบส 1 ตัวบริเวณต้นยีนจึงมักอันตรายกว่าการแทนที่เบส 1 ตัว`,
 o:[`A deletion removes a whole chromosome`,`A deletion causes a frameshift, changing every codon after it`,`A deletion always produces a stop codon immediately`,`A substitution never changes the protein`],
 a:1,
 s:[["Frameshift","DNA อ่านทีละ 3 เบส (reading frame) ถ้าเบสหายไป 1 ตัว กรอบการอ่านจะ<span class='key'>เลื่อน</span> → <b>ทุก codon หลังจุดนั้นเปลี่ยน</b> → ลำดับกรดอะมิโนเปลี่ยนมาก โปรตีนมักทำงานไม่ได้"],
    ["Substitution","เปลี่ยนแค่ codon เดียว → เปลี่ยนกรดอะมิโนอย่างมาก 1 ตัว หรืออาจ<b>ไม่เปลี่ยนเลย</b> เพราะหลาย codon ให้กรดอะมิโนเดียวกัน (degenerate code)"],
    ["ตัดตัวเลือก","A: เบสเดียวไม่ใช่ทั้งโครโมโซม; C: ไม่เสมอไป; D: substitution <b>อาจ</b>เปลี่ยนโปรตีนได้ (เช่น sickle cell)"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:H2,d:2,
 q:`An mRNA codon is <b>AUG</b>. What is the anticodon on the tRNA that binds to it?`,
 th:`codon บน mRNA คือ <b>AUG</b> anticodon บน tRNA ที่มาจับคู่คืออะไร`,
 o:[`AUG`,`TAC`,`ATG`,`UAC`],
 a:3,
 s:[["หลักการ","ระหว่าง <b>translation</b> ที่ไรโบโซม anticodon ของ tRNA จับคู่แบบ complementary กับ codon ของ mRNA (RNA กับ RNA → ใช้ <span class='key'>U</span> ไม่มี T)"],
    ["จับคู่","A→U, U→A, G→C → <b>UAC</b>"],
    ["ตัดตัวเลือก","B, C: มี T ซึ่งไม่พบใน RNA"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

/* ---------- Protein transport & endomembrane ---------- */
{t:H3,d:1,
 q:`Where does translation of <b>all</b> proteins begin?`,
 th:`การแปลรหัส (translation) ของโปรตีน<b>ทุกชนิด</b>เริ่มต้นที่ใด`,
 o:[`On free ribosomes in the cytoplasm`,`Inside the Golgi apparatus`,`Inside the nucleus`,`In the lumen of the rough ER`],
 a:0,
 s:[["หลักการ","ไม่ว่าโปรตีนจะไปอยู่ที่ใด (cytoplasm, nucleus, membrane, หลั่งออก) <span class='key'>translation เริ่มที่ free ribosome ใน cytoplasm เสมอ</span>"],
    ["จากนั้น","ถ้าสายเพปไทด์มี <b>signal peptide</b> ที่ปลาย N ไรโบโซมจะถูกนำไปเกาะ ER ภายหลัง (จึงเห็นเป็น rough ER)"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:H3,d:2,
 q:`A protein is fully translated on a free ribosome and has <b>no</b> targeting signal sequence. Where will it end up? Which is an example?`,
 th:`โปรตีนที่แปลรหัสจนเสร็จบน free ribosome และ<b>ไม่มี</b>ลำดับสัญญาณนำส่ง จะไปอยู่ที่ใด และข้อใดเป็นตัวอย่าง`,
 o:[`Secreted out of the cell — e.g. insulin`,`In the cell membrane — e.g. a sodium channel`,`In the cytoplasm — e.g. enzymes of glycolysis`,`In the nucleus — e.g. histones`],
 a:2,
 s:[["หลักการ","mRNA ออกจากนิวเคลียส → ไรโบโซมแปลรหัสจนครบ → <span class='key'>ถ้าไม่มีสัญญาณพิเศษ โปรตีนจะอยู่ใน cytoplasm</span> (default)"],
    ["ตัวอย่าง","เอนไซม์ glycolysis, เอนไซม์ใน cell signalling, เอนไซม์ metabolism ของกรดอะมิโน"],
    ["ตัดตัวเลือก","A, B ต้องมี signal peptide และผ่าน ER; D ต้องมี Nuclear Localisation Signal (NLS)"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:H3,d:2,
 q:`How does a protein made in the cytoplasm enter the nucleus?`,
 th:`โปรตีนที่สร้างใน cytoplasm เข้าสู่นิวเคลียสได้อย่างไร`,
 o:[`It diffuses directly through the phospholipid bilayer of the nuclear envelope`,`Its nuclear localisation signal (NLS) binds importin, and the complex passes through a nuclear pore complex`,`It is packaged into vesicles by the Golgi which fuse with the nucleus`,`Its signal peptide is recognised by SRP, which takes it to the nucleus`],
 a:1,
 s:[["ขั้นตอน","<ol><li>Cargo protein ถูกแปลรหัสจนครบใน cytoplasm</li><li>ลำดับ <span class='key'>NLS (Nuclear Localisation Signal)</span> จับกับโปรตีนตัวพา <b>importin</b></li><li>Complex ผ่านเข้านิวเคลียสทาง <b>nuclear pore complex (NPC)</b></li><li>ในนิวเคลียส <b>RanGTP</b> จับ importin → ปล่อย cargo แล้ว importin ถูกส่งกลับออกไปใช้ใหม่</li></ol>"],
    ["ตัดตัวเลือก","A: โปรตีนใหญ่และมีขั้ว ผ่าน bilayer ไม่ได้; C: Golgi ไม่ได้ส่งโปรตีนเข้านิวเคลียส; D: SRP นำไปที่ <b>ER</b>"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:H3,d:3,
 q:`Secreted proteins are made by <b>co-translational translocation</b>. Which description is correct?`,
 th:`โปรตีนที่หลั่งออกนอกเซลล์ถูกสร้างด้วย <b>co-translational translocation</b> ข้อใดอธิบายถูกต้อง`,
 o:[`The protein is completely made in the cytoplasm, then imported into the ER by importin`,`The protein is made inside the Golgi apparatus`,`The ribosome makes the protein inside the nucleus and exports it through pores`,`Translation starts in the cytoplasm; a signal peptide at the N-terminus is recognised by SRP, which takes the ribosome to the ER where translation is completed`],
 a:3,
 s:[["ความหมายของคำ","<b>co-translational</b> = เกิดขึ้น<b>ระหว่าง</b>ที่ยังแปลรหัสอยู่ (ยังไม่เสร็จ)"],
    ["ขั้นตอน","<ol><li>Translation เริ่มที่ cytoplasm แต่<b>ยังไม่เสร็จ</b></li><li>ปลาย N ของเพปไทด์มี <span class='key'>signal peptide</span> ซึ่งถูกจดจำโดย <span class='key'>SRP (signal recognition particle)</span></li><li>SRP พา ribosome–mRNA–peptide complex ไปเกาะ ER แล้วแปลรหัสต่อจนเสร็จ โปรตีนเข้าไปใน lumen ของ ER (หรือฝังในเยื่อ ถ้าเป็น transmembrane protein)</li></ol>"],
    ["ตัดตัวเลือก","A: importin ใช้กับนิวเคลียส และการเข้า ER แบบนี้ไม่ใช่ co-translational; B, C: ผิดตำแหน่ง"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:H3,d:2,
 q:`Which sequence shows the route of a secreted protein (e.g. a digestive enzyme) after it is made?`,
 th:`ลำดับใดแสดงเส้นทางของโปรตีนที่ถูกหลั่งออกนอกเซลล์ (เช่น เอนไซม์ย่อยอาหาร) หลังถูกสร้าง`,
 o:[`Golgi → rough ER → nucleus → cell membrane`,`Rough ER → nucleus → vesicle → cell membrane`,`Rough ER → vesicle → Golgi apparatus → secretory vesicle → cell membrane`,`Mitochondrion → Golgi → vesicle → cell membrane`],
 a:2,
 s:[["เส้นทาง (protein trafficking)","<span class='key'>Rough ER</span> (สังเคราะห์/พับ) → <b>transport vesicle</b> → <span class='key'>Golgi</span> เข้าที่ cis face (ดัดแปลง คัดแยก) ออกที่ trans face → <b>secretory vesicle</b> → หลอมกับ cell membrane → <b>exocytosis</b> สู่ extracellular matrix"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:H3,d:2,
 q:`Vesicles budding from the Golgi apparatus are carried towards the cell surface along microtubules. Which motor protein moves them in this direction?`,
 th:`เวสิเคิลที่แตกหน่อจากกอลจิถูกขนไปยังผิวเซลล์ตามไมโครทิวบูล โปรตีนมอเตอร์ใดเคลื่อนพาไปในทิศนี้`,
 o:[`Kinesin`,`Dynein`,`Importin`,`Haemoglobin`],
 a:0,
 s:[["Motor proteins บน microtubules","<ul><li><span class='key'>Kinesin</span> → เคลื่อน vesicle <b>ออกไปยังขอบเซลล์</b> (cell periphery / cell surface)</li><li><span class='key'>Dynein</span> → เคลื่อนใน<b>ทิศตรงข้าม</b> เข้าหาใจกลางเซลล์/ER เช่น vesicle ที่นำโปรตีนกลับไป ER</li></ul>ช่วยจำ: <b>K</b>inesin = <b>K</b>ick out, <b>D</b>ynein = <b>D</b>rag in"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:H3,d:2,
 q:`What allows a transport vesicle to fuse with the cell surface membrane and release its cargo?`,
 th:`อะไรทำให้เวสิเคิลขนส่งหลอมรวมกับเยื่อหุ้มเซลล์และปล่อยสิ่งที่บรรจุอยู่ออกไป`,
 o:[`SRP binding to the signal peptide`,`v-SNARE on the vesicle binding to t-SNARE on the target membrane`,`Importin binding to RanGTP`,`Osmosis of water into the vesicle`],
 a:1,
 s:[["กลไก SNARE","<span class='key'>v-SNARE</span> (v = vesicle) บนเวสิเคิล จับกับ <span class='key'>t-SNARE</span> (t = target) บนเยื่อเป้าหมาย → ดึงสองเยื่อเข้าใกล้กัน → เยื่อหลอมรวม → ปล่อยโปรตีนออก (exocytosis)"],
    ["ตัดตัวเลือก","A = การนำไรโบโซมไป ER; C = การนำเข้านิวเคลียส; D ไม่เกี่ยว"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

/* ---------- Passive transport ---------- */
{t:H4,d:1,
 q:`Which process is a type of <b>passive</b> transport?`,
 th:`กระบวนการใดเป็นการลำเลียงแบบ <b>passive</b>`,
 o:[`The sodium–potassium pump`,`Endocytosis`,`Na<sup>+</sup>/glucose symport`,`Facilitated diffusion`],
 a:3,
 s:[["แยก passive / active","<ul><li><b>Passive</b> (ไม่ใช้ ATP, เกิดขึ้นเอง spontaneously): simple diffusion, <span class='key'>facilitated diffusion</span>, osmosis</li><li><b>Active</b> (ใช้พลังงาน): primary active (Na<sup>+</sup>–K<sup>+</sup> pump), secondary active (Na<sup>+</sup>/glucose symport), bulk transport (endo/exocytosis)</li></ul>"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:H4,d:2,
 q:`Why does glucose need channel or carrier proteins to cross the cell membrane?`,
 th:`ทำไมกลูโคสจึงต้องอาศัยโปรตีนช่องหรือโปรตีนตัวพาในการผ่านเยื่อหุ้มเซลล์`,
 o:[`It is relatively large and polar, so it cannot pass easily through the hydrophobic core of the bilayer`,`It is charged like sodium ions`,`It always moves against its concentration gradient`,`It is a lipid that dissolves in the membrane`],
 a:0,
 s:[["Permeability","ใจกลางของ phospholipid bilayer เป็นหาง fatty acid ที่<span class='key'>ไม่ชอบน้ำ (hydrophobic)</span> โมเลกุลเล็กไม่มีขั้ว (O<sub>2</sub>, CO<sub>2</sub>) ผ่านได้ง่าย แต่<b>โมเลกุลใหญ่และมีขั้ว</b>อย่างกลูโคสผ่านได้ยาก"],
    ["Facilitated diffusion","กลูโคสจึงผ่านโดย <b>carrier protein</b> (เช่น GLUT) ลงตาม concentration gradient ไม่ใช้ ATP"],
    ["ตัดตัวเลือก","B: กลูโคสไม่มีประจุ (uncharged); C: facilitated diffusion ไปตาม gradient; D: กลูโคสเป็นคาร์โบไฮเดรต"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:H4,d:1,
 q:`Which substance crosses the membrane by <b>simple diffusion</b> directly through the phospholipid bilayer?`,
 th:`สารใดผ่านเยื่อหุ้มเซลล์ด้วย <b>simple diffusion</b> โดยผ่านชั้น phospholipid โดยตรง`,
 o:[`Sodium ions`,`Glucose`,`Oxygen`,`Proteins`],
 a:2,
 s:[["หลักการ","Simple diffusion ผ่าน bilayer ได้เฉพาะโมเลกุล <span class='key'>เล็กและไม่มีขั้ว/ไม่มีประจุ</span> เช่น O<sub>2</sub>, CO<sub>2</sub>"],
    ["ตัดตัวเลือก","A: ไอออนมีประจุ ต้องผ่าน channel; B: ใช้ carrier (facilitated); D: ใหญ่มาก ต้องใช้ bulk transport"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:H4,d:3,
 q:`The inside of a resting cell is negatively charged relative to the outside, and Na<sup>+</sup> concentration is much higher outside. Which statement describes the movement of Na<sup>+</sup> when Na<sup>+</sup> channels open?`,
 th:`ภายในเซลล์ขณะพักมีประจุลบเมื่อเทียบกับภายนอก และความเข้มข้น Na<sup>+</sup> ภายนอกสูงกว่ามาก เมื่อช่อง Na<sup>+</sup> เปิด ข้อใดอธิบายการเคลื่อนที่ของ Na<sup>+</sup> ได้ถูกต้อง`,
 o:[`Na<sup>+</sup> moves out, because the electrical gradient is stronger than the chemical gradient`,`Na<sup>+</sup> moves in, because the chemical and electrical gradients both point into the cell`,`Na<sup>+</sup> does not move, because the two gradients cancel out`,`Na<sup>+</sup> moves in only if ATP is supplied`],
 a:1,
 s:[["Chemical gradient","Na<sup>+</sup> ข้างนอกมาก ข้างในน้อย → แรงขับทางเคมีชี้<b>เข้า</b>เซลล์"],
    ["Electrical gradient","Na<sup>+</sup> มีประจุบวก ถูกดึงไปฝั่ง<b>ลบ</b> (ภายในเซลล์) → แรงขับทางไฟฟ้าชี้<b>เข้า</b>เซลล์"],
    ["Electrochemical gradient","ทั้งสองแรง<span class='key'>เสริมกัน (reinforce)</span> → Na<sup>+</sup> แพร่เข้าเซลล์อย่างแรงผ่าน channel ไม่ต้องใช้ ATP (เป็น facilitated diffusion)"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:H4,d:3,
 q:`K<sup>+</sup> concentration is higher inside the cell than outside, and the inside of the cell is negative. If the electrical gradient acting on K<sup>+</sup> is <b>greater</b> than its chemical gradient, what will be the net movement of K<sup>+</sup> through open K<sup>+</sup> channels?`,
 th:`K<sup>+</sup> ภายในเซลล์มีความเข้มข้นสูงกว่าภายนอก และภายในเซลล์เป็นลบ ถ้า electrical gradient ที่กระทำต่อ K<sup>+</sup> <b>มากกว่า</b> chemical gradient การเคลื่อนสุทธิของ K<sup>+</sup> ผ่านช่อง K<sup>+</sup> จะเป็นอย่างไร`,
 o:[`Out of the cell`,`No movement at all, ever`,`Out of the cell, using ATP`,`Into the cell`],
 a:3,
 s:[["แรงสองทิศ","<ul><li><b>Chemical gradient</b>: K<sup>+</sup> ในเซลล์มาก → ผลักให้ K<sup>+</sup> <b>ออก</b></li><li><b>Electrical gradient</b>: K<sup>+</sup> ประจุบวกถูกดึงเข้าหาภายในที่เป็นลบ → ดึง K<sup>+</sup> <b>เข้า</b></li></ul>สองแรง<span class='key'>ตรงข้ามกัน</span> แรงที่มากกว่าเป็นตัวกำหนดทิศ"],
    ["ตัดสิน","electrical &gt; chemical → electrochemical gradient ชี้<b>เข้า</b> → K<sup>+</sup> เคลื่อนเข้าเซลล์ (ถ้า chemical &gt; electrical จะออก; ถ้าเท่ากันไม่มีการเคลื่อนสุทธิ = equilibrium)"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:H4,d:2,
 q:`Red blood cells are placed in a <b>hypertonic</b> salt solution. What happens?`,
 th:`นำเม็ดเลือดแดงใส่ในสารละลายเกลือที่เป็น <b>hypertonic</b> จะเกิดอะไรขึ้น`,
 o:[`Water enters; cells swell and burst (lysis)`,`No net movement of water`,`Water leaves by osmosis; cells shrink and become crenated`,`Salt enters by osmosis; cells become turgid`],
 a:2,
 s:[["Tonicity","<ul><li><b>Hypertonic</b>: ความเข้มข้นตัวละลายภายนอก <b>&gt;</b> ภายในเซลล์ → น้ำ<b>ออก</b></li><li><b>Isotonic</b>: เท่ากัน → ไม่มีการเคลื่อนสุทธิ</li><li><b>Hypotonic</b>: ภายนอก &lt; ภายใน → น้ำ<b>เข้า</b></li></ul>"],
    ["ผลต่อเม็ดเลือดแดง","น้ำออกโดย osmosis → เซลล์หดเหี่ยวขอบหยัก เรียกว่า <span class='key'>crenated</span> (เซลล์สัตว์ไม่ใช้คำว่า plasmolysed)"],
    ["ตัดตัวเลือก","A = hypotonic; B = isotonic; D: osmosis คือการเคลื่อนของน้ำ และ turgid ใช้กับเซลล์พืช"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:H4,d:2,
 q:`Which pair of changes would <b>both</b> increase the rate of diffusion across a membrane?`,
 th:`การเปลี่ยนแปลงคู่ใดที่<b>ทั้งสองอย่าง</b>เพิ่มอัตราการแพร่ผ่านเยื่อ`,
 o:[`Steeper concentration gradient and higher temperature`,`Thicker membrane and larger surface area`,`Lower temperature and steeper concentration gradient`,`Lower permeability and larger surface area`],
 a:0,
 s:[["ปัจจัยที่มีผลต่อการแพร่","<ul><li>Concentration gradient ↑ → อัตรา ↑</li><li>Surface area ↑ → อัตรา ↑</li><li>Distance (ความหนา) ↑ → อัตรา <b>↓</b></li><li>Temperature ↑ → อัตรา ↑</li><li>Permeability ↑ → อัตรา ↑</li><li>(ไอออน) electrical gradient มีผลด้วย</li></ul>"],
    ["ตรวจแต่ละคู่","B: เยื่อหนาขึ้นลดอัตรา; C: อุณหภูมิต่ำลงลดอัตรา; D: permeability ต่ำลงลดอัตรา"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

/* ---------- Active transport ---------- */
{t:H5,d:1,
 q:`Which statement correctly describes active transport?`,
 th:`ข้อใดอธิบายการลำเลียงแบบใช้พลังงาน (active transport) ได้ถูกต้อง`,
 o:[`Movement of water down a water potential gradient`,`Movement of substances against a concentration gradient using energy from respiration (ATP) and carrier proteins`,`Movement of gases through the phospholipid bilayer`,`Movement of substances down a concentration gradient through channels`],
 a:1,
 s:[["นิยาม","<span class='key'>Active transport</span> = ลำเลียงสาร<b>จากความเข้มข้นต่ำ → สูง</b> (against the gradient) ใช้ <b>ATP</b> จาก respiration และใช้ <b>carrier proteins</b> เป็นกระบวนการ nonspontaneous ต้องมี coupled reaction"],
    ["ตัดตัวเลือก","A = osmosis; C = simple diffusion; D = facilitated diffusion"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:H5,d:2,
 q:`For each ATP molecule used, what does the Na<sup>+</sup>–K<sup>+</sup> pump (Na<sup>+</sup>–K<sup>+</sup> ATPase) move?`,
 th:`ต่อ ATP 1 โมเลกุล ปั๊ม Na<sup>+</sup>–K<sup>+</sup> ลำเลียงไอออนอย่างไร`,
 o:[`2 Na<sup>+</sup> into the cell and 3 K<sup>+</sup> out`,`3 Na<sup>+</sup> into the cell and 2 K<sup>+</sup> out`,`3 Na<sup>+</sup> out of the cell and 2 K<sup>+</sup> into the cell`,`1 Na<sup>+</sup> out and 1 K<sup>+</sup> in`],
 a:2,
 s:[["Primary active transport","Na<sup>+</sup>–K<sup>+</sup> ATPase ใช้ ATP <b>โดยตรง</b> เป็นโปรตีนตัวพาที่ลำเลียง 2 สารพร้อมกัน"],
    ["ทิศทาง","<span class='key'>3 Na<sup>+</sup> ออก</span> และ <span class='key'>2 K<sup>+</sup> เข้า</span> ต่อ 1 ATP — ทั้งสองทวน gradient ของตัวเอง (Na<sup>+</sup> ข้างนอกสูง, K<sup>+</sup> ข้างในสูง)"],
    ["ผลตามมา","ประจุบวกออกมากกว่าเข้า → ช่วยให้ภายในเซลล์เป็นลบ และสร้าง Na<sup>+</sup> gradient ที่ใช้ขับ secondary active transport"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:H5,d:3,
 q:`In the small intestine, glucose is absorbed into epithelial cells against its concentration gradient by a Na<sup>+</sup>/glucose symporter. What directly provides the energy for moving glucose?`,
 th:`ในลำไส้เล็ก กลูโคสถูกดูดเข้าเซลล์เยื่อบุทวน concentration gradient โดย Na<sup>+</sup>/glucose symporter พลังงานที่ใช้ขนกลูโคสมาจากอะไร<b>โดยตรง</b>`,
 o:[`ATP hydrolysed by the symporter itself`,`Osmosis of water into the cell`,`Glucose diffusing down its own gradient`,`Na<sup>+</sup> diffusing into the cell down its electrochemical gradient`],
 a:3,
 s:[["Secondary active transport","การลำเลียงสารหนึ่ง<b>ทวน gradient</b> โดยใช้พลังงานที่เก็บอยู่ใน<span class='key'>gradient ของอีกสารหนึ่ง</span> ไม่ได้ใช้ ATP โดยตรง"],
    ["Energy view","Na<sup>+</sup> (สูงข้างนอก) แพร่เข้าผ่าน symporter → ปล่อยพลังงาน → <b>couple</b> กับการดันกลูโคส (ต่ำ → สูง) เข้าเซลล์พร้อมกัน (co-transport, ทิศเดียวกัน = symport)"],
    ["ใครสร้าง Na<sup>+</sup> gradient","Na<sup>+</sup>–K<sup>+</sup> pump (primary active) ที่ด้าน basal ของเซลล์ ใช้ ATP คอยสูบ Na<sup>+</sup> ออก ATP จึงถูกใช้<b>ทางอ้อม</b>"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:H5,d:3,
 q:`A drug inhibits the Na<sup>+</sup>–K<sup>+</sup> pump in intestinal epithelial cells. What is the most likely effect on glucose absorption by the Na<sup>+</sup>/glucose symporter?`,
 th:`ยาชนิดหนึ่งยับยั้งปั๊ม Na<sup>+</sup>–K<sup>+</sup> ในเซลล์เยื่อบุลำไส้ ผลที่น่าจะเกิดกับการดูดกลูโคสผ่าน Na<sup>+</sup>/glucose symporter คืออะไร`,
 o:[`It decreases, because the Na<sup>+</sup> concentration gradient into the cell is no longer maintained`,`It increases, because more Na<sup>+</sup> stays outside the cell`,`It is unaffected, because the symporter does not use ATP`,`It increases, because more ATP is available for the symporter`],
 a:0,
 s:[["เชื่อมโยง","Symporter ต้องอาศัย Na<sup>+</sup> ข้างนอก<b>สูง</b> ข้างใน<b>ต่ำ</b> ซึ่งปั๊ม Na<sup>+</sup>–K<sup>+</sup> คอยรักษาไว้"],
    ["ผล","ปั๊มหยุด → Na<sup>+</sup> ที่แพร่เข้ามาสะสมในเซลล์ → <span class='key'>gradient ลดลงเรื่อย ๆ</span> → พลังงานขับ symporter ลด → ดูดกลูโคสได้น้อยลง"],
    ["ตัดตัวเลือก","C เป็นกับดัก: แม้ symporter ไม่ใช้ ATP โดยตรง แต่<b>พึ่งพา</b>งานของปั๊มที่ใช้ ATP"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:H5,d:2,
 q:`Which statement about bulk transport (endocytosis and exocytosis) is correct?`,
 th:`ข้อความใดเกี่ยวกับ bulk transport (เอนโดไซโทซิสและเอกโซไซโทซิส) ถูกต้อง`,
 o:[`It is passive and needs no energy`,`It uses ATP to move vesicles and change the shape of the membrane`,`It only moves small ions such as Na<sup>+</sup>`,`It happens only in plant cells`],
 a:1,
 s:[["Bulk transport","ลำเลียงสาร<b>ขนาดใหญ่</b>หรือปริมาณมากผ่านเยื่อด้วย<b>เวสิเคิล</b> ใช้ <span class='key'>ATP</span> เพื่อเคลื่อน vesicle และเปลี่ยนรูปร่างเยื่อ"],
    ["ตัวอย่าง","<ul><li><b>Exocytosis</b>: หลั่งเอนไซม์ย่อยอาหาร, insulin, สารสื่อประสาท</li><li><b>Endocytosis</b>: white blood cell (phagocyte) กลืนกินแบคทีเรีย (phagocytosis)</li></ul>"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:H5,d:2,
 q:`Which process <b>always</b> requires a partially permeable membrane <b>and</b> does not need energy from the cell?`,
 th:`กระบวนการใด<b>ต้องมี</b>เยื่อเลือกผ่าน<b>เสมอ</b> <b>และ</b>ไม่ต้องใช้พลังงานจากเซลล์`,
 o:[`Diffusion`,`Active transport`,`Osmosis`,`Exocytosis`],
 a:2,
 s:[["ตารางเปรียบเทียบ","<div class='tbl'><table><tr><th></th><th>Diffusion</th><th>Osmosis</th><th>Active transport</th></tr><tr><td>ผ่านเยื่อ?</td><td>ไม่จำเป็น</td><td><b>ใช่</b></td><td>ใช่</td></tr><tr><td>พลังงาน</td><td>ไม่ใช้</td><td><b>ไม่ใช้</b></td><td>ใช้</td></tr><tr><td>ตัวอย่าง</td><td>O<sub>2</sub> จากถุงลมสู่เลือด</td><td>ขนรากดูดน้ำ</td><td>Na<sup>+</sup>–K<sup>+</sup> pump</td></tr></table></div>"],
    ["วิเคราะห์","Diffusion เกิดได้โดยไม่มีเยื่อ (เช่น น้ำหอมกระจายในห้อง) แต่ <span class='key'>osmosis</span> ตามนิยามต้องผ่าน partially permeable membrane และเป็น passive"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

/* ---------- Carbohydrates, lipids, proteins ---------- */
{t:H6,d:2,
 q:`Two glucose molecules join to form maltose. What type of bond is formed and what type of reaction is this?`,
 th:`กลูโคส 2 โมเลกุลรวมกันเป็นมอลโทส เกิดพันธะชนิดใด และเป็นปฏิกิริยาประเภทใด`,
 o:[`Peptide bond; hydrolysis`,`Ester bond; condensation`,`Hydrogen bond; hydrolysis`,`Glycosidic bond; condensation`],
 a:3,
 s:[["ปฏิกิริยา","C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> → C<sub>12</sub>H<sub>22</sub>O<sub>11</sub> + <b>H<sub>2</sub>O</b> — มีการปล่อยน้ำ = <span class='key'>condensation (dehydration)</span>"],
    ["ชนิดพันธะ","พันธะระหว่างน้ำตาล = <span class='key'>glycosidic bond</span>; ในโปรตีน = peptide bond; ในไขมัน = ester bond"],
    ["กลับด้าน","การสลาย maltose โดยเติมน้ำ = <b>hydrolysis</b>"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:H6,d:2,
 q:`Lactose cannot be absorbed by the small intestine until it has been digested into glucose and galactose. Why?`,
 th:`แล็กโทสยังดูดซึมผ่านลำไส้เล็กไม่ได้จนกว่าจะถูกย่อยเป็นกลูโคสและกาแล็กโทส เพราะเหตุใด`,
 o:[`Lactose (a disaccharide) is too large to be absorbed; the membrane transport proteins carry monosaccharides`,`Lactose is a protein and must be digested by protease`,`Lactose is insoluble in water`,`Glucose and galactose are larger than lactose`],
 a:0,
 s:[["วิเคราะห์","Lactose เป็น <b>disaccharide</b> (glucose + galactose) โมเลกุลใหญ่เกินกว่าจะผ่านเยื่อหุ้มเซลล์เยื่อบุลำไส้ได้ และโปรตีนตัวพา (เช่น Na<sup>+</sup>/glucose symporter) รองรับ <span class='key'>monosaccharides</span>"],
    ["การย่อย","เอนไซม์ <b>lactase</b> hydrolyse พันธะ glycosidic → glucose + galactose → ดูดซึมได้ (คนที่ขาด lactase จะ lactose intolerant)"],
    ["ตัดตัวเลือก","B: lactose เป็นคาร์โบไฮเดรต; C: lactose ละลายน้ำได้; D: กลับด้าน"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:H6,d:1,
 q:`What is an oligosaccharide?`,
 th:`โอลิโกแซ็กคาไรด์คืออะไร`,
 o:[`A single sugar unit such as glucose`,`A carbohydrate made of 3–10 monosaccharides joined by glycosidic bonds`,`A carbohydrate made of thousands of glucose units`,`A lipid containing a sugar group`],
 a:1,
 s:[["ประเภทคาร์โบไฮเดรต","<ul><li><b>Monosaccharide</b>: 1 หน่วย (glucose, fructose, galactose — hexose มี C 6 อะตอม)</li><li><b>Disaccharide</b>: 2 หน่วย (maltose, sucrose, lactose)</li><li><span class='key'>Oligosaccharide</span>: 3–10 หน่วย</li><li><b>Polysaccharide</b>: หลายร้อย–หลายพันหน่วย (starch, glycogen, cellulose)</li></ul>"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:H6,d:3,
 q:`Why do phospholipids form a bilayer in water?`,
 th:`ทำไมฟอสโฟลิพิดจึงเรียงตัวเป็นสองชั้น (bilayer) ในน้ำ`,
 o:[`Because they contain three fatty acids joined to glycerol by ester bonds`,`Because they are made of amino acids joined by peptide bonds`,`Because each has a hydrophilic phosphate head and two hydrophobic fatty acid tails; heads face water and tails face inwards`,`Because they are steroids with four carbon rings`],
 a:2,
 s:[["โครงสร้าง","Triglyceride = glycerol + <b>3</b> fatty acids; <span class='key'>Phospholipid</span> = glycerol + <b>2</b> fatty acids + <b>phosphate group</b> (แทน fatty acid 1 ตัว)"],
    ["สมบัติ","หัว phosphate <b>hydrophilic</b> (ชอบน้ำ) + หาง fatty acid <b>hydrophobic</b> (ไม่ชอบน้ำ) = โมเลกุล amphipathic"],
    ["การเรียงตัว","ในน้ำ หัวหันออกหาน้ำทั้งด้านนอกเซลล์และใน cytoplasm หางหันเข้าหากันตรงกลาง → <b>bilayer</b> = โครงสร้างของเยื่อหุ้มเซลล์"],
    ["ตัดตัวเลือก","A = triglyceride; B = protein; D = steroid"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:H6,d:1,
 q:`Which of these is a lipid derivative (steroid)?`,
 th:`ข้อใดเป็นอนุพันธ์ของลิพิด (สเตียรอยด์)`,
 o:[`Insulin`,`Glycogen`,`Triglyceride`,`Cholesterol`],
 a:3,
 s:[["ลิพิด 3 ประเภท","<ol><li><b>Simple lipid</b> — triglyceride</li><li><b>Complex lipid</b> — phospholipid</li><li><span class='key'>Lipid derivative (steroid)</span> — cholesterol, sex hormones (testosterone, oestrogen), cortisol</li></ol>"],
    ["ตัดตัวเลือก","A: insulin เป็นโปรตีน (ฮอร์โมนเพปไทด์); B: polysaccharide; C: simple lipid"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:H6,d:2,
 q:`What determines the final three-dimensional shape of a protein, such as the shape of an enzyme's active site?`,
 th:`อะไรเป็นตัวกำหนดรูปร่างสามมิติสุดท้ายของโปรตีน เช่น รูปร่างของ active site ของเอนไซม์`,
 o:[`The number of glucose units in the chain`,`The sequence of amino acids (primary structure), which is coded by DNA`,`The number of ester bonds`,`The amount of water the protein absorbs`],
 a:1,
 s:[["โครงสร้างกรดอะมิโน","กรดอะมิโนมี <b>amine group (−NH<sub>2</sub>)</b>, <b>carboxyl group (−COOH)</b> และ <span class='key'>R group</span> ที่ต่างกัน 20 แบบ ต่อกันด้วย <b>peptide bond</b>"],
    ["ระดับโครงสร้าง","ลำดับกรดอะมิโน (<b>primary</b>) → พับเป็น α-helix/β-sheet (<b>secondary</b>) → ม้วนพับเป็นรูป 3 มิติเฉพาะ (<b>tertiary</b>) ด้วยพันธะระหว่าง R groups — ลำดับจึงกำหนดรูปร่าง"],
    ["เชื่อมโยง","DNA → mRNA → ลำดับกรดอะมิโน → รูปร่าง → หน้าที่ (เหตุที่ mutation เปลี่ยนการทำงานของเอนไซม์ได้)"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

/* ---------- Enzymes & inhibitors ---------- */
{t:H7,d:1,
 q:`How do enzymes increase the rate of a reaction?`,
 th:`เอนไซม์เพิ่มอัตราการเกิดปฏิกิริยาได้อย่างไร`,
 o:[`By lowering the activation energy needed for the reaction`,`By raising the temperature of the reaction mixture`,`By supplying extra energy to the substrate`,`By being used up and changed into product`],
 a:0,
 s:[["Activation energy","= พลังงาน<b>ต่ำสุด</b>ที่ต้องใช้เพื่อเริ่มปฏิกิริยา (เปรียบเหมือนเนินเขาที่ต้องเข็นหินข้าม)"],
    ["บทบาทเอนไซม์","เอนไซม์เป็น <b>biological catalyst</b> <span class='key'>ลด activation energy</span> (เหมือนตัดยอดเขาออก) ปฏิกิริยาจึงเกิดง่ายและเร็วขึ้นที่อุณหภูมิร่างกาย"],
    ["ตัดตัวเลือก","B, C: เอนไซม์ไม่ได้ให้ความร้อน/พลังงาน; D: catalyst ไม่ถูกใช้หมด นำกลับมาใช้ใหม่ได้"],
    ["สรุป","✅ <b>คำตอบ A</b>"]]},

{t:H7,d:3,
 q:`Enzyme P has a K<sub>m</sub> of 2 mmol/dm³ and enzyme Q has a K<sub>m</sub> of 10 mmol/dm³ for the same substrate. Which statement is correct?`,
 th:`เอนไซม์ P มี K<sub>m</sub> = 2 mmol/dm³ และเอนไซม์ Q มี K<sub>m</sub> = 10 mmol/dm³ สำหรับ substrate เดียวกัน ข้อใดถูกต้อง`,
 o:[`Q has the higher affinity for the substrate`,`P always has the higher V<sub>max</sub>`,`P has the higher affinity: it reaches half its maximum rate at a lower substrate concentration`,`K<sub>m</sub> is the maximum rate of the reaction`],
 a:2,
 s:[["นิยาม","<ul><li><span class='key'>V<sub>max</sub></span> = อัตราเร็วสูงสุดของปฏิกิริยา (เมื่อ active site อิ่มตัว)</li><li><span class='key'>K<sub>m</sub></span> (Michaelis constant) = ความเข้มข้นของ substrate ที่ทำให้อัตราเป็น <b>½ V<sub>max</sub></b></li></ul>"],
    ["แปลความหมาย","K<sub>m</sub> <b>ต่ำ</b> → ใช้ substrate น้อยก็ถึงครึ่งหนึ่งของอัตราสูงสุด → เอนไซม์จับ substrate ได้ดี = <b>affinity สูง</b>"],
    ["ตัดตัวเลือก","A: กลับด้าน; B: K<sub>m</sub> ไม่ได้บอก V<sub>max</sub>; D: สับสนระหว่าง K<sub>m</sub> กับ V<sub>max</sub>"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]},

{t:H7,d:2,
 q:`A <b>competitive</b> inhibitor slows an enzyme reaction. Which statement is correct?`,
 th:`ตัวยับยั้งแบบ<b>แข่งขัน (competitive inhibitor)</b> ทำให้ปฏิกิริยาช้าลง ข้อใดถูกต้อง`,
 o:[`It binds to a site away from the active site and permanently changes its shape`,`Its effect cannot be reduced by adding more substrate`,`It lowers the V<sub>max</sub> of the enzyme`,`It has a shape similar to the substrate and binds to the active site; its effect is reduced by increasing substrate concentration`],
 a:3,
 s:[["กลไก","Competitive inhibitor มี<span class='key'>รูปร่างคล้าย substrate</span> → เข้าจับที่ <b>active site</b> แข่งกับ substrate → enzyme–substrate complex เกิดน้อยลง"],
    ["เมื่อเพิ่ม substrate","substrate มีจำนวนมากกว่า inhibitor → ชนะการแข่งขัน → อัตรากลับมาใกล้เดิม → <b>V<sub>max</sub> เท่าเดิม</b> แต่ <b>K<sub>m</sub> สูงขึ้น</b> (ต้องใช้ substrate มากขึ้นกว่าจะถึง ½ V<sub>max</sub>)"],
    ["ตัดตัวเลือก","A, B, C เป็นลักษณะของ <b>non-competitive</b> inhibitor"],
    ["สรุป","✅ <b>คำตอบ D</b>"]]},

{t:H7,d:3,
 q:`A <b>non-competitive</b> inhibitor is added to an enzyme. What happens as substrate concentration is increased to a very high level?`,
 th:`เติมตัวยับยั้งแบบ<b>ไม่แข่งขัน (non-competitive)</b> ลงในเอนไซม์ เมื่อเพิ่มความเข้มข้นของ substrate จนสูงมาก จะเกิดอะไรขึ้น`,
 o:[`The rate rises to the same V<sub>max</sub> as without the inhibitor`,`The rate stays below the original V<sub>max</sub>, because the inhibitor binds elsewhere and changes the active site shape`,`The inhibitor is pushed out of the active site by the substrate`,`The enzyme is denatured by the substrate`],
 a:1,
 s:[["กลไก","Non-competitive inhibitor จับที่<span class='key'>ตำแหน่งอื่น (allosteric site)</span> ไม่ใช่ active site → ทำให้ <b>active site เปลี่ยนรูป</b> → substrate เข้าจับไม่ได้"],
    ["ผลของการเพิ่ม substrate","substrate ไม่ได้แข่งตำแหน่งเดียวกับ inhibitor → เพิ่มเท่าไรก็ไม่ช่วย เอนไซม์ที่ถูกยับยั้งเท่ากับหายไป → <b>V<sub>max</sub> ลดลง</b>"],
    ["ตัดตัวเลือก","A, C = competitive; D: substrate ไม่ทำให้ denature"],
    ["สรุป","✅ <b>คำตอบ B</b>"]]},

{t:H7,d:2,
 q:`On a graph of rate against substrate concentration, the rate levels off at high substrate concentrations. Why?`,
 th:`บนกราฟอัตราการเกิดปฏิกิริยาเทียบกับความเข้มข้นของ substrate อัตราคงที่เมื่อ substrate มีความเข้มข้นสูง เพราะเหตุใด`,
 o:[`The enzyme has been denatured by the substrate`,`The substrate has all been used up`,`All the active sites are occupied, so enzyme concentration is now the limiting factor`,`The product has stopped forming`],
 a:2,
 s:[["ช่วงต้นกราฟ","substrate น้อย มี active site ว่างเหลือ → เพิ่ม substrate → เกิด enzyme–substrate complex มากขึ้น → อัตราเพิ่ม (substrate เป็น limiting factor)"],
    ["ช่วงราบ","<span class='key'>active sites ถูกใช้หมดแล้ว (saturated)</span> → เพิ่ม substrate ไม่ช่วย → อัตรา = V<sub>max</sub> ตอนนี้<b>ความเข้มข้นของเอนไซม์</b>เป็น limiting factor"],
    ["ตัดตัวเลือก","A: substrate ไม่ทำให้ denature; B: substrate มีมาก ไม่ได้หมด; D: product ยังเกิดอยู่ในอัตราคงที่"],
    ["สรุป","✅ <b>คำตอบ C</b>"]]}
];

const written = [
{t:H2,m:4,
 q:`According to the central dogma, do all of us have exactly the same proteins in our bodies? Explain your answer.`,
 th:`ตามหลักการ central dogma เราทุกคนมีโปรตีนในร่างกายเหมือนกันทุกประการหรือไม่ จงอธิบาย`,
 ms:[`No (except identical twins)`,
     `Central dogma: DNA → (transcription) → mRNA → (translation) → protein`,
     `Different people have different alleles / DNA base sequences`,
     `So mRNA codons differ, giving different amino acid sequences`,
     `Different amino acid sequence → different folding / shape → different (versions of) proteins, e.g. blood group antigens`],
 ans:`<p>No. The central dogma states that genetic information flows from DNA to mRNA by transcription and from mRNA to protein by translation. Different people inherit different alleles, so the base sequence of their DNA is slightly different. This gives different codons in the mRNA and therefore a different sequence of amino acids. A different amino acid sequence folds into a different shape, so some proteins differ between people (for example the antigens that decide blood group). Only identical twins have the same DNA and so the same proteins.</p>`,
 tip:`คำตอบที่ได้คะแนนเต็มต้องเชื่อมให้เป็น<b>ห่วงโซ่เหตุผล</b>: DNA ต่าง → mRNA ต่าง → กรดอะมิโนต่าง → รูปร่างต่าง → โปรตีนต่าง`},

{t:H2,m:6,
 q:`Describe how the information in a gene is used to make a polypeptide. Refer to transcription and translation in your answer.`,
 th:`อธิบายว่าข้อมูลในยีนถูกใช้สร้างพอลิเพปไทด์อย่างไร โดยกล่าวถึง transcription และ translation`,
 ms:[`Transcription occurs in the nucleus: the DNA unwinds / hydrogen bonds break, and one strand is used as a template`,
     `Free RNA nucleotides pair with complementary bases (A–U, T–A, C–G) and RNA polymerase joins them to form mRNA`,
     `mRNA leaves the nucleus through a nuclear pore and attaches to a ribosome`,
     `Each codon (three bases) codes for one amino acid`,
     `tRNA molecules carry specific amino acids; the tRNA anticodon pairs with the complementary mRNA codon`,
     `Adjacent amino acids are joined by peptide bonds; this continues until a stop codon`],
 ans:`<p><b>Transcription</b> takes place in the nucleus. The part of the DNA containing the gene unwinds as the hydrogen bonds between bases break, and one strand acts as a template. Free RNA nucleotides line up by complementary base pairing (A with U, T with A, C with G, G with C) and RNA polymerase joins them to make a molecule of mRNA. The mRNA leaves the nucleus through a nuclear pore.</p><p><b>Translation</b> takes place at a ribosome in the cytoplasm. The mRNA is read in codons of three bases, each coding for one amino acid. tRNA molecules bring specific amino acids; the anticodon on each tRNA pairs with the complementary codon on the mRNA. The ribosome joins neighbouring amino acids with peptide bonds, and the polypeptide grows until a stop codon is reached.</p>`,
 tip:`แยกสองย่อหน้าให้ชัด: <b>ที่ไหน</b> (nucleus / ribosome) · <b>แม่แบบคืออะไร</b> (DNA / mRNA) · <b>ใครทำ</b> (RNA polymerase / tRNA + ribosome) · <b>ผลลัพธ์</b> (mRNA / polypeptide)`},

{t:H2,m:4,
 q:`One strand of a DNA molecule has the base sequence <b>5′ – A T G C C T A G G – 3′</b>.<br>(a) Write the sequence of the complementary DNA strand. [1]<br>(b) If the strand shown is used as the template, write the mRNA sequence produced. [1]<br>(c) Explain why DNA replication is described as semi-conservative. [2]`,
 th:`DNA สายหนึ่งมีลำดับเบส ATGCCTAGG (a) เขียนลำดับสาย DNA ที่เป็นคู่สม (b) ถ้าใช้สายนี้เป็นแม่แบบ mRNA ที่ได้มีลำดับอย่างไร (c) อธิบายว่าทำไมการจำลอง DNA เรียกว่า semi-conservative`,
 ms:[`(a) T A C G G A T C C`,
     `(b) U A C G G A U C C`,
     `(c) The two strands separate and each acts as a template for a new strand`,
     `(c) Each new DNA molecule contains one original (parental) strand and one newly synthesised strand`],
 ans:`<p>(a) TAC GGA TCC<br>(b) UAC GGA UCC (same as (a) but U replaces T)</p><p>(c) During replication, the hydrogen bonds break and the two strands separate. Each original strand acts as a template, and free nucleotides pair with it by complementary base pairing. So each new DNA molecule is made of one original strand and one new strand, meaning half of the original molecule is conserved.</p>`,
 tip:`(a) กับ (b) ต่างกันเพียง T ↔ U — เป็นการเช็คว่ารู้ว่า RNA ไม่มี thymine`},

{t:H2,m:4,
 q:`Two mutations occur in the same gene. Mutation 1 is a substitution of one base. Mutation 2 is a deletion of one base near the start of the gene.<br>Explain why mutation 2 is likely to have a greater effect on the protein than mutation 1.`,
 th:`เกิดการกลายพันธุ์ 2 แบบในยีนเดียวกัน แบบที่ 1 แทนที่เบส 1 ตัว แบบที่ 2 เบสหายไป 1 ตัวบริเวณต้นยีน อธิบายว่าทำไมแบบที่ 2 มักส่งผลต่อโปรตีนมากกว่า`,
 ms:[`The genetic code is read in triplets (codons)`,
     `Substitution changes only one codon, so at most one amino acid changes (or none, as the code is degenerate)`,
     `Deletion causes a frameshift – every codon after the mutation is changed`,
     `So many amino acids change / an early stop codon may form, so the protein folds into a different shape and may not function`],
 ans:`<p>The base sequence is read in triplets called codons. A substitution alters only one codon, so at most one amino acid is changed, and sometimes none because several codons code for the same amino acid. A deletion near the start of the gene shifts the reading frame (a frameshift), so every codon after the deletion is read differently. Many amino acids are changed, or a stop codon may appear early, so the protein has a very different shape and probably cannot function.</p>`},

{t:H3,m:6,
 q:`Insulin is a protein hormone secreted by cells in the pancreas.<br>Describe the route taken by insulin from its synthesis to its release from the cell. Include the roles of the signal peptide, organelles and transport proteins involved.`,
 th:`อินซูลินเป็นฮอร์โมนโปรตีนที่หลั่งจากเซลล์ตับอ่อน อธิบายเส้นทางของอินซูลินตั้งแต่ถูกสังเคราะห์จนถูกปล่อยออกนอกเซลล์ รวมถึงบทบาทของ signal peptide ออร์แกเนลล์ และโปรตีนขนส่งที่เกี่ยวข้อง`,
 ms:[`Translation begins on a free ribosome in the cytoplasm`,
     `A signal peptide at the N-terminus is recognised by SRP (signal recognition particle)`,
     `SRP takes the ribosome to the rough ER; translation continues into the ER lumen (co-translational translocation)`,
     `Protein is carried in a transport vesicle from the ER to the cis face of the Golgi apparatus`,
     `Golgi modifies, sorts and packages it into secretory vesicles (leaving the trans face)`,
     `Vesicles are moved along microtubules by kinesin towards the cell surface`,
     `v-SNARE on the vesicle binds t-SNARE on the cell membrane; membranes fuse and insulin is released by exocytosis`],
 ans:`<p>Translation of insulin begins on a free ribosome in the cytoplasm. The first part of the polypeptide made, at the N-terminus, is a signal peptide, which is recognised by the signal recognition particle (SRP). The SRP takes the ribosome–mRNA complex to the rough ER, where translation is completed and the protein enters the ER lumen (co-translational translocation).</p><p>The protein is carried in a transport vesicle to the cis face of the Golgi apparatus, where it is modified, sorted and packaged into secretory vesicles that bud from the trans face. The kinesin motor protein moves these vesicles along microtubules towards the cell surface. The v-SNARE on the vesicle binds to the t-SNARE on the cell surface membrane, the membranes fuse and insulin is released from the cell by exocytosis, which uses ATP.</p>`,
 tip:`เขียนตามลำดับเวลาเหมือนเล่าเรื่อง: ribosome → SRP → rough ER → vesicle → Golgi (cis → trans) → kinesin/microtubule → SNARE → exocytosis มี 7 จุดให้เก็บ 6 คะแนน`},

{t:H3,m:4,
 q:`(a) Give <b>one</b> example of a protein that functions inside the nucleus. [1]<br>(b) Describe how this protein is transported from the cytoplasm into the nucleus. [3]`,
 th:`(a) ยกตัวอย่างโปรตีนที่ทำงานในนิวเคลียส 1 ชนิด (b) อธิบายว่าโปรตีนนี้ถูกขนส่งจาก cytoplasm เข้าสู่นิวเคลียสอย่างไร`,
 ms:[`(a) Any one: histones / DNA polymerase / RNA polymerase / transcription factors / helicase`,
     `(b) The protein is fully translated on a free ribosome in the cytoplasm`,
     `(b) Its nuclear localisation signal (NLS) binds to importin`,
     `(b) The importin–cargo complex passes through a nuclear pore complex`,
     `(b) In the nucleus RanGTP binds importin, releasing the cargo; importin is exported to be reused`],
 ans:`<p>(a) DNA polymerase (also accepted: histones, RNA polymerase, transcription factors).</p><p>(b) DNA polymerase is fully translated on a free ribosome in the cytoplasm. It contains a nuclear localisation signal (NLS) sequence, which binds to the transport protein importin. The importin–protein complex moves through a nuclear pore complex into the nucleus. Inside the nucleus, RanGTP binds to importin, causing it to release the protein; the importin–RanGTP is then exported to the cytoplasm so importin can be reused.</p>`,
 tip:`ตัวอย่างโปรตีนในนิวเคลียสที่ปลอดภัย: <b>DNA polymerase</b> (ใช้ในการจำลอง DNA) และ <b>RNA polymerase</b> (ใช้ใน transcription) — เชื่อมกับเรื่อง molecular genetics ได้`},

{t:H4,m:4,
 q:`In a resting nerve cell, the inside of the membrane is negative compared with the outside. Na<sup>+</sup> concentration is higher outside the cell, and K<sup>+</sup> concentration is higher inside the cell.<br>Using the idea of chemical, electrical and electrochemical gradients, explain the direction in which Na<sup>+</sup> ions move when Na<sup>+</sup> channels open, and why the direction of K<sup>+</sup> movement is less certain.`,
 th:`ในเซลล์ประสาทขณะพัก ภายในเยื่อเป็นลบเมื่อเทียบกับภายนอก Na<sup>+</sup> ภายนอกสูงกว่า ส่วน K<sup>+</sup> ภายในสูงกว่า ใช้แนวคิด chemical, electrical และ electrochemical gradient อธิบายทิศทางการเคลื่อนของ Na<sup>+</sup> เมื่อช่อง Na<sup>+</sup> เปิด และทำไมทิศทางของ K<sup>+</sup> จึงไม่แน่นอนเท่า`,
 ms:[`Na<sup>+</sup>: chemical gradient is inwards (high outside → low inside)`,
     `Na<sup>+</sup>: electrical gradient is also inwards (positive ion attracted to negative inside); gradients reinforce, so Na<sup>+</sup> moves in`,
     `K<sup>+</sup>: chemical gradient is outwards but electrical gradient is inwards – they are opposite`,
     `The net direction depends on which gradient is larger (electrochemical gradient); if chemical > electrical, K<sup>+</sup> moves out, and vice versa`],
 ans:`<p>For Na<sup>+</sup>, the concentration is higher outside, so the chemical gradient drives Na<sup>+</sup> into the cell. Na<sup>+</sup> is positive and the inside is negative, so the electrical gradient also pulls it into the cell. The two gradients reinforce each other, so the electrochemical gradient is strongly inwards and Na<sup>+</sup> diffuses into the cell through the channels.</p><p>For K<sup>+</sup>, the chemical gradient pushes it out of the cell because it is more concentrated inside, but the electrical gradient pulls it into the negative inside. The two gradients act in opposite directions, so the net movement depends on which is greater: if the chemical gradient is larger, K<sup>+</sup> moves out; if the electrical gradient is larger, it moves in; if they are equal there is no net movement.</p>`,
 tip:`วาดลูกศร 2 อันต่อไอออนในกระดาษทด (chemical กับ electrical) แล้วดูว่าชี้ทางเดียวกัน (เสริมกัน) หรือตรงข้าม (หักล้าง)`},

{t:H5,m:5,
 q:`Glucose is absorbed from the lumen of the small intestine into epithelial cells by a Na<sup>+</sup>/glucose symporter, even when the glucose concentration inside the cell is higher than in the lumen.<br>Explain how this happens, and why the process is described as <b>secondary</b> active transport.`,
 th:`กลูโคสถูกดูดจากช่องลำไส้เล็กเข้าสู่เซลล์เยื่อบุผ่าน Na<sup>+</sup>/glucose symporter แม้ความเข้มข้นกลูโคสในเซลล์สูงกว่าในช่องลำไส้ อธิบายว่าเกิดได้อย่างไร และทำไมจึงเรียกว่า secondary active transport`,
 ms:[`Na<sup>+</sup>–K<sup>+</sup> pump uses ATP to pump Na<sup>+</sup> out of the epithelial cell (3 Na<sup>+</sup> out, 2 K<sup>+</sup> in)`,
     `This keeps Na<sup>+</sup> concentration low inside the cell, maintaining a Na<sup>+</sup> gradient from lumen into the cell`,
     `Na<sup>+</sup> diffuses into the cell down its gradient through the symporter`,
     `Glucose is carried in at the same time (co-transport) against its concentration gradient, using energy from Na<sup>+</sup> movement`,
     `Secondary because ATP is not used directly by the symporter; it uses the gradient created by the primary active Na<sup>+</sup>–K<sup>+</sup> pump`],
 ans:`<p>The Na<sup>+</sup>–K<sup>+</sup> pump on the epithelial cell uses ATP to pump three Na<sup>+</sup> out of the cell for every two K<sup>+</sup> it takes in. This keeps the Na<sup>+</sup> concentration inside the cell low, so there is a steep Na<sup>+</sup> gradient from the lumen into the cell. Na<sup>+</sup> diffuses into the cell down this gradient through the Na<sup>+</sup>/glucose symporter, and the energy released is coupled to moving glucose into the cell at the same time, against its concentration gradient.</p><p>This is secondary active transport because the symporter does not hydrolyse ATP itself; it uses energy stored in the Na<sup>+</sup> gradient, which was set up by the primary active transport of the Na<sup>+</sup>–K<sup>+</sup> pump.</p>`,
 tip:`คำสำคัญที่ผู้ตรวจมองหา: <b>coupled</b>, <b>down its gradient</b> (Na<sup>+</sup>), <b>against its gradient</b> (glucose), <b>ATP used indirectly</b>`},

{t:H6,m:4,
 q:`Lactose is a disaccharide found in milk.<br>(a) Name the two monosaccharides that make up lactose. [1]<br>(b) Name the bond that joins them and the type of reaction that breaks this bond during digestion. [2]<br>(c) Suggest why people who do not produce lactase get digestive problems after drinking milk. [1]`,
 th:`แล็กโทสเป็นไดแซ็กคาไรด์ในนม (a) บอกมอโนแซ็กคาไรด์ 2 ชนิดที่ประกอบเป็นแล็กโทส (b) บอกชื่อพันธะและชนิดของปฏิกิริยาที่สลายพันธะนี้ระหว่างการย่อย (c) เสนอเหตุผลว่าทำไมคนที่ไม่สร้าง lactase จึงมีปัญหาทางเดินอาหารหลังดื่มนม`,
 ms:[`(a) Glucose and galactose`,
     `(b) Glycosidic bond`,
     `(b) Hydrolysis (water is added)`,
     `(c) Lactose is not digested so cannot be absorbed; it stays in the intestine where bacteria ferment it (gas) / it lowers water potential so water enters the gut by osmosis (diarrhoea)`],
 ans:`<p>(a) Glucose and galactose.</p><p>(b) A glycosidic bond, which is broken by hydrolysis (a water molecule is added), catalysed by lactase.</p><p>(c) Without lactase, lactose cannot be broken into monosaccharides, so it cannot be absorbed. It stays in the intestine, where bacteria ferment it and produce gas, and it lowers the water potential of the gut contents so water moves in by osmosis, causing diarrhoea.</p>`},

{t:H7,m:5,
 q:`The table shows the rate of an enzyme reaction at different substrate concentrations, with and without an inhibitor.
 <div class='tbl'><table><tr><th>Substrate / mmol dm⁻³</th><td>1</td><td>2</td><td>5</td><td>10</td><td>20</td><td>40</td></tr><tr><th>Rate, no inhibitor</th><td>20</td><td>33</td><td>56</td><td>71</td><td>83</td><td>91</td></tr><tr><th>Rate, with inhibitor</th><td>8</td><td>14</td><td>29</td><td>45</td><td>63</td><td>77</td></tr></table></div>
 (a) Is the inhibitor competitive or non-competitive? Use data from the table to explain your answer. [3]<br>(b) Explain how this type of inhibitor reduces the rate of reaction. [2]`,
 th:`ตารางแสดงอัตราการเกิดปฏิกิริยาของเอนไซม์ที่ความเข้มข้น substrate ต่าง ๆ เมื่อมีและไม่มีตัวยับยั้ง (a) ตัวยับยั้งเป็นแบบแข่งขันหรือไม่แข่งขัน ใช้ข้อมูลในตารางอธิบาย (b) อธิบายว่าตัวยับยั้งประเภทนี้ลดอัตราการเกิดปฏิกิริยาได้อย่างไร`,
 ms:[`(a) Competitive`,
     `(a) At low substrate the inhibitor has a large effect: at 1 mmol dm⁻³ the rate falls from 20 to 8 (60 % lower)`,
     `(a) At high substrate the effect is much smaller: at 40 mmol dm⁻³, 91 vs 77 (about 15 % lower) – rate approaches the same V<sub>max</sub>`,
     `(b) The inhibitor has a similar shape to the substrate and binds to the active site`,
     `(b) Fewer enzyme–substrate complexes form; more substrate out-competes the inhibitor (K<sub>m</sub> increases, V<sub>max</sub> unchanged)`],
 ans:`<p>(a) Competitive. At a low substrate concentration of 1 mmol dm⁻³ the inhibitor reduces the rate from 20 to 8, a 60 % decrease. At 40 mmol dm⁻³ the rate is only reduced from 91 to 77, about 15 %. As substrate concentration increases the effect of the inhibitor gets smaller and the rate approaches the same maximum, which shows that the substrate is competing with the inhibitor.</p><p>(b) The inhibitor has a shape similar to the substrate, so it binds to the active site and blocks it. Fewer enzyme–substrate complexes can form, so the rate falls. When there is much more substrate than inhibitor, the substrate is more likely to occupy the active sites, so V<sub>max</sub> is unchanged but K<sub>m</sub> increases.</p>`,
 tip:`การใช้ข้อมูล (\"use data\") ต้อง<b>อ้างตัวเลขจริงอย่างน้อย 2 คู่</b> และคำนวณการเปลี่ยนแปลงเปรียบเทียบ ไม่ใช่แค่พูดว่า \"ลดลง\"`}
];

window.EXAMS.hbio = {
  title:"Human Biology", code:"Human Biology · Unit 1 Mock Paper",
  topics:["Cell structure & levels of organisation","Molecular genetics: DNA, replication, transcription, translation, mutation","Protein transport & endomembrane system","Passive & active transport (electrochemical gradient, Na⁺–K⁺ pump)","Carbohydrates, lipids, proteins","Enzymes, Km / Vmax & inhibitors"],
  mcq, written
};
})();
